#!/usr/bin/env python3
"""Build rev14 sentiment JSON from 1725 entity build (226 entities).
Carries rev13 (1435 build, 192 entities) forward; adds 21 new + 13 updates.
Keeps output under 100K chars for read-back safety."""
import json, os

OUT = "/home/p62operator/.openclaw/workspace-ns/04-DATA-AND-SOURCES/sentiment-analysis/2026-07-19/sentiment-20260720-0130.json"

meta = {
    "version": "revision-14",
    "date": "2026-07-19",
    "generated": "2026-07-20T01:30:00+08:00",
    "generated_utc": "2026-07-19T17:30:00Z",
    "tlp": "AMBER",
    "mission": "PRN Negeri Sembilan 2026 Sentiment Analysis",
    "agent": "PRN NS 2026 Sentiment Analysis Agent (cron)",
    "entity_build": "processed-entities/2026-07-19/entities-20260719-1725.json (226 entities, 12 cycles, 14 critical/103 priority/109 normal). Finalized 01:24 MYT 20 Jul. Supersedes 205-entity 1435 build used by rev13 (finalized 22:41 MYT 19 Jul). +21 new entities + 13 updates from cycles 153300 (23:33 MYT) + 171500 (01:15 MYT 20 Jul, Harian Metro feed recovery HTTP 200, 17 new full-text). KEY NEW: Khaled Nordin (Umno VP) 4-publisher 'KO habis'/'kacau daun' (NST+BH+Metro+FMT) = FIRST BN-VP hard-news corroboration of 'Bersatu kacau daun'; Loke 'PH sasar 23 kerusi' (5-publisher, PH-attributed => PRIORITY not CRITICAL); PN 'kongsi pentas' = 4th cooperation stage; Hassan Karim PKR dissent; April 19 royal crisis + 14 Umno ADUN backdoor = election origin; Loke 'campaign on policies' + 'not in Rantau'; Aminuddin small-group + honest defense; N.19 Johol; MCA told-her-to-stay-home viral (9,100 likes).",
    "prior_revision_file": "sentiment-analysis/2026-07-19/sentiment-20260719-2330.json",
    "prior_revision": "revision-13 (2026-07-19T23:30:00+08:00, 192 entities, 13 critical/32 priority)",
    "score_convention": "SIGNED (-1.0 to +1.0). Negative = -1.0 to < -0.20; Neutral = -0.20 to +0.20 (marginal/mixed band); Positive = > +0.20 to +1.0.",
    "pir_weights": "PIR-06=2.0, PIR-16=1.8, PIR-07=1.3, non-priority=1.0",
    "critical_threshold": "Sharp sentiment shift >30% change for any PIR-06 entity; Bersatu sharp-negative internal-fracture signal = [CRITICAL]. PIR-16 CRITICAL if hard-news corroborates 'Bersatu exit imminent?' OR Bersatu-attributed 'sasar bentuk kerajaan negeri'.",
    "election_context": "PRN Negeri Sembilan 2026 - Campaign Day 1 (Nomination 18 Jul closed; Day-1 19 Jul). Polling 1 Aug; early voting 28 Jul; BN manifesto launch 24 Jul (DUN Linggi + Pertang); PH manifesto launch 20 Jul (Amirudin Shari, Klana Resort). Electorate 889,490 (103 candidates, 36 seats; simple-majority threshold 19).",
    "director_cycle": "19 Jul 17:25 MYT (4th carry-forward)",
    "entity_count": 235,
    "critical_count": 13,
    "priority_count": 48,
    "none_count": 174
}

# Each entity: (entity, pir_tag, sentiment, score, trend, alert, source_count, rationale)
E = []
def a(entity, pir_tag, sentiment, score, trend, alert, sc, rat):
    E.append({"entity":entity,"pir_tag":pir_tag,"sentiment":sentiment,"score":score,"trend":trend,"alert":alert,"source_count":sc,"rationale":rat})

# ===== PIR-06 CRITICAL (carried + adjusted) =====
a("Muhyiddin Yassin","PIR-06","negative",-0.92,"declining","critical",11,"rev13 -0.90 -> rev14 -0.92. SIXTH converging [CRITICAL] trigger: Khaled Nordin (Umno VP/Defence Minister) 4-publisher 'Pastikan Bersatu KO habis-habis' + 'kacau daun' (NST+BH+Metro+FMT 23:49-00:16 MYT) — FIRST BN-VP-level hard-news call for Bersatu's ELECTORAL ELIMINATION. Plus 153300 'Bersatu now sole opposition party' (The Vibes 18 Jul) self-positioning. Now 6 triggers: lebih-hebat, sasar-kerajaan solo 24-seat, PN-toksik, quorum+RoS, Hamzah rebuke, Khaled elimination call. Bersatu sharp-negative internal-fracture signal CONFIRMED -> [CRITICAL].")
a("Bersatu","PIR-06","negative",-0.88,"declining","critical",12,"rev13 -0.86 -> rev14 -0.88. SEVENTH trigger: Khaled 'KO habis' + 'kacau daun' hard-news 4-publisher. 24 own-logo seats + lebih-hebat + sasar-kerajaan + PN-toksik + quorum + Hamzah rebuke + Khaled elimination. Bersatu sharp-negative internal-fracture signal CONFIRMED -> [CRITICAL].")
a("Bersatu-PN fracture (3-sided)","PIR-06","negative",-0.89,"declining","critical",9,"rev13 -0.88 -> rev14 -0.89. Khaled (BN VP) elimination call adds a BN-voice to the 3-sided fracture (Bersatu vs PAS/Wawasan vs PN-MT, now + BN-VP anti-Bersatu). Intra-opposition + intra-coalition warfare.")
a("PN-removal-of-Bersatu thread","PIR-06","negative",-0.90,"declining","critical",8,"rev13 -0.89 -> rev14 -0.90. Khaled 'KO habis' electoral-elimination rhetoric pushes toward removal trajectory (BN-VP voice). Formal PN-MT expulsion notice STILL NOT issued (11th consecutive pass). Trajectory: pre-threshold; most likely Bersatu voluntary realignment AFTER 1 Aug poll.")
a("lebih hebat new coalition","PIR-06","negative",-0.78,"declining","critical",6,"Carried rev13. Muhyiddin (Sinar 17 Jul + BH + Metro + MalaysiaGazette + Newswav + Buletin TV3): NEW 'lebih hebat' coalition after PRN NS. >50% viral amplification fires. No formal launch 18-19 Jul — remains hint/bayangan stage. PRU16 realignment vehicle.")
a("sasar bentuk kerajaan negeri (Bersatu solo governing bid)","PIR-16","negative",-0.80,"declining","critical",2,"Carried rev13. MalaysiaGazette + Sinar (19 Jul 15:37-15:53): Bersatu sasar bentuk kerajaan negeri, tanding 24 kerusi (EXCEEDS simple-majority 19). Director rule: hard-news corroboration = [CRITICAL]. 171500 NOTE: Loke 'PH sasar 23 kerusi' is PH-attributed safe-majority (scored separately PRIORITY); the Bersatu-attributed 24-seat solo version remains the [CRITICAL] signal. DIRECTLY CONTRADICTS PN-MB-concedes-to-BN + joint-manifesto.")
a("toxic PN (Muhyiddin framing)","PIR-06","negative",-0.78,"declining","critical",6,"Carried rev13. 171500 Metro BM full text corroborates Muhyiddin 'PN sudah jadi parti toksik' + Hamzah rebuttal. Multi-outlet hard-news. Director 'toxic PN' = [CRITICAL] rule. Intra-opposition warfare Wawasan(Hamzah) vs Bersatu(Muhyiddin).")
a("kuorum (Bersatu MPT quorum dispute)","PIR-06","negative",-0.65,"declining","critical",7,"Carried rev13. Kiandee (11 Jul) vs Radzi (11 Jul): disputed baseline 49 vs 23 MPT members, Clause 13.12. Sanjeevan frames 'alasan sekat Bersatu bertanding'. Dispute CONTESTED not resolved. Director-designated [CRITICAL].")
a("RoS complaint disrupting PN seat negotiations","PIR-06","negative",-0.62,"declining","critical",3,"Carried rev13. Tun Faisal (Bersatu info chief, Sikamat candidate) confirms RoS complaint disrupted PN seat negotiations (Sinar 15 Jul). Kiandee warns 'administrative limbo'. RoS-intervention-adjacent [CRITICAL] sub-threshold; NOT full RoS action.")
a("Bersatu Supreme Leadership (MPT)","PIR-06","negative",-0.72,"declining","critical",5,"Carried rev13. Kiandee claims 27/49 MPT gone -> ~22 remain -> NO quorum. Radzi rebutted: 12/23 sufficient. Disputed baseline UNRESOLVED.")
a("PN Supreme Council (PN-MT)","PIR-06","negative",-0.55,"declining","critical",3,"Carried rev13. Kiandee called PN-MT to convene re: Bersatu. Closest-to-formal-PN-action signal. No PN-MT expulsion notice 11 cycles.")
a("pecat Tang Jay Son (Gerakan)","PIR-06","negative",-0.40,"declining","critical",2,"Carried rev13. Gerakan expelled Tang Jay Son secara serta-merta (Awani 18 Jul 20:22) for contesting on Bersatu ticket in Rahang. Director flag: any 'pecat' = [CRITICAL]-tier. Bersatu attracting Gerakan defectors -> intra-PN friction.")
a("Ronald Kiandee","PIR-06","negative",-0.25,"declining","critical",3,"Carried rev13. Suspended Bersatu VP; cited Clause 13.12, 27/49 MPT gone. Confirmed 'former Bersatu VP' at NST merge-machinery event. Director-designated [CRITICAL] trigger.")

# ===== PIR-06 PRIORITY (carried + new) =====
a("Perikatan Nasional (PN)","PIR-06","neutral",0.30,"stable","none",5,"Mixed: ops deepening (gabung+joint manifesto+kongsi pentas+MB concession) vs toksik attack by Muhyiddin. PN=11 seats (PAS+Gerakan+MIPP+Wawasan). Wawasan+PAS bloc stabilizes PN against Bersatu exit. Stable.")
a("PAS","PIR-06","negative",-0.22,"improving","none",5,"rev13 -0.25 -> rev14 -0.22 (improving). Hamzah defense + Khaled pro-BN-PN + kongsi pentas. Hadi inclusive coalition-building. Severed Bersatu ties 8 Jun but remains in PN. Net improving.")
a("Hadi Awang","PIR-06","negative",-0.22,"improving","none",5,"rev13 -0.25 -> rev14 -0.22 (improving). Hamzah defense offsets blame-shift. 'Bukan retorik' PRU16 model + 'Malay-Muslim unity with non-extreme partners'. Makmal-politik consolidating.")
a("Barisan Nasional (BN)","PIR-06","positive",0.40,"improving","none",8,"rev13 +0.35 -> rev14 +0.40. Khaled 'gelombang Melayu ke BN' + 'KO habis' + joint-manifesto + gabung-jentera + kongsi-pentas + PN concedes MB. 25 NS seats. Tok Mat resign-compliance. Strong pro-BN-PN stance. Stable positive, improving on cooperation formalization (4 stages).")
a("UMNO","PIR-06","neutral",0.18,"declining","none",6,"BN lead party; 25 NS seats; receives PN-conceded MB. Khaled VP-voice anti-Bersatu + pro-BN-PN. Internal 'derhaka' friction (Jalaluddin rebuttal); Onn Hafiz 'DNA UMNO bukan penderhaka'. Rafizi: NS friction 'tanda awal kesan luar jangka kepada UMNO'. Slightly positive but declining.")
a("MCA","PIR-16","negative",-0.48,"declining","priority",7,"rev13 -0.45 -> rev14 -0.48. TRIPLE pressure: Loke 'biggest loser' mockery (external) + Saw Yee Fung told to skip NS + Chong Sin Woon WhatsApp 'you don't need to come' (internal, viral 9,100 likes). Wee/Mah Hang Soon containment line. Defensive posture deepening.")
a("MIC","PIR-06","neutral",0.10,"stable","none",1,"BN component; Hadi-named non-extreme partner. 'Lebih banyak lebih baik'.")
a("DHPP","PIR-06","neutral",0.10,"stable","none",1,"BN component; Hadi-named non-extreme partner alongside MCA, MIC.")
a("MIPP (Malaysian Indian People's Party)","PIR-06","neutral",0.0,"stable","none",1,"PN component; contesting Lukut (one of 3 MCA-ceded seats). Sathes Kumar Nilameham candidate.")
a("Gerakan","PIR-06","neutral",-0.10,"stable","none",2,"PN component; expelled Tang Jay Son for contesting on Bersatu ticket. 'Pecat' enforcement. Contesting Bukit Kepayang (Lee Boon Shian vs DAP Nicole Tan).")
a("Pejuang","PIR-06","neutral",-0.05,"stable","none",1,"Admitted into PN alongside Wawasan (FMT 22 Jun). Component-party churn.")
a("Wawasan (Parti Wawasan Negara)","PIR-06","neutral",-0.15,"stable","priority",3,"Director-flagged. Hamzah's party; admitted to PN. VP Wan Saiful at joint-manifesto meeting. Ridzuan Ahmad = Gemas candidate. Component-party churn signal. Wawasan+PAS bloc visibly stabilizes PN vs Bersatu exit.")
a("Hamzah Zainudin","PIR-06","neutral",-0.20,"declining","priority",4,"Carried rev13. Wawasan president (sacked Bersatu Feb 2026). PUBLICLY REBUKED Muhyiddin 'don't call PAS toxic, remember who helped you become PM' (FMT 19:46 4-outlet). Met PN candidates Razali+Dr Rafie. First leader-to-leader intra-opposition warfare signal.")
a("Annuar Musa","PIR-06","negative",-0.35,"declining","priority",4,"PN info chief; confirmed BN-PN JOINT MANIFESTO (NST 20:31 + BH 19:58). 'Impossible for PN to fulfil Bersatu's NS demands'. Muhyiddin fires back at Annuar. Opinion-tier exit amplifier + joint-manifesto carrier.")
a("Ahmad Samsuri Mokhtar (Samsuri)","PIR-06","neutral",0.15,"stable","none",3,"PN chairman; approved PN-BN talks contradicting Muhyiddin. PRU16 framing. Joint-manifesto + kongsi-pentas attendee. Slightly positive coalition-building.")
a("Tun Faisal Ismail Aziz","PIR-06","neutral",-0.10,"stable","none",3,"N.13 Sikamat Bersatu candidate. Filed RoS complaint disrupting PN seat negotiations (Sinar 15 Jul). 'Machiavellian' politics accusation vs PAS. Bersatu high-profile NS face.")
a("Radzi Jidin","PIR-06","neutral",-0.10,"stable","none",3,"Formal quorum rebuttal (FMT 11 Jul 17:37): 'jalan seperti biasa', 12/23 sufficient. Key defender of Bersatu legitimacy vs Kiandee/RoS line.")
a("Ridzuan Ahmad","PIR-06","neutral",0.05,"stable","none",4,"Bersatu-quit figure; now Wawasan/Gemas candidate. BN Tampin ops rooms assist. His quit = Bersatu-cohesion negative; personally neutral strategic move.")
a("Ahmad Zahid Hamidi (Zahid)","PIR-06","neutral",0.20,"stable","none",3,"Awani: 'prestasi BN-PN penentu jajaran PRU16' reinforces makmal-politik. 'BN-PN merely an understanding, no agreements' (The Vibes). Aligns with Hadi 'bukan retorik'.")
a("Sufian Maradzi","PIR-07","neutral",0.10,"stable","none",1,"BN Seri Menanti candidate; named by Jalaluddin as MB-stock (alongside Jalaluddin, Tok Mat).")
a("Mohd Isam Mohd Isa","PIR-06","positive",0.35,"stable","none",2,"BH: all BN ops rooms in Gemas/Tampin open to assist PN (Wawasan) candidates. 'Not a political merger.' 'We do not want any sabotage.' Seat-level cooperation CONFIRMED.")
a("Abu Bakar Hamzah","PIR-06","neutral",-0.20,"stable","none",1,"Bersatu Perlis chief / former MB Perlis resigned from MPT — adds to 'lagi pemimpin Bersatu letak jawatan' churn feeding Kiandee's quorum case.")
a("Marzuki","PIR-06","neutral",0.05,"stable","none",1,"'Korum MPT Bersatu tidak perlu dijadikan isu' (Newswav 13 Jul). Quorum-deescalation voice.")
a("Wong Chia Zhen","PIR-06","neutral",-0.10,"stable","none",1,"Gerakan sec-gen; issued Tang Jay Son expulsion — 'pelanggaran disiplin parti yang serius'.")
a("Takiyuddin Hassan","PIR-06","neutral",0.15,"stable","none",2,"PN secretary-general; present at gabung-jentera (NST 19:49) + joint-manifesto (NST 20:31) + kongsi-pentas. PN operational lead; reinforces formalization.")
a("Muhammad Sanusi Md Nor","PIR-06","neutral",0.10,"stable","none",1,"PN election director (Kedah MB). 'Gelombang biru mendahului gelombang merah'. Joint-manifesto attendee at KOMPAS.")
a("Bersatu goes solo under own logo (24 seats)","PIR-06","negative",-0.62,"stable","none",7,"Full-text confirmed across FMT, NST, Awani, Metro. Breaks PN state consensus; recreates vote-splitting. 24 EXCEEDS simple-majority 19. Strongest operational-split; NOT formal expulsion.")
a("PAS severed political ties with Bersatu (June 8)","PIR-06","negative",-0.40,"stable","none",3,"Operational fact. Both remain in PN; used same logo for Johor. Underpins operational-split narrative.")
a("Bersatu advised to quit PN with Gerakan/MIPP","PIR-06","negative",-0.55,"declining","priority",2,"Lau Zhe Wei (IIUM, FMT): Bersatu should quit PN + take Gerakan/MIPP. Corroborates Muhyiddin lebih-hebat hint.")
a("Bersatu heading for wipeout in NS (analyst consensus)","PIR-16","negative",-0.72,"declining","priority",4,"rev13 -0.70 -> rev14 -0.72. Azeem Fazwan 'in no position to win seats going solo.' Azmil Tayeb 'all people see is infighting.' Wan Saiful 'kacau daun' + Khaled 'KO habis'. Reinforces exit trajectory.")
a("Selangor PAS Youth","PIR-06","negative",-0.30,"stable","priority",1,"'Bersatu should leave PN' (FMT 11 Jun). Amplifier of Bersatu-exit narrative from PAS side.")
a("gabung jentera (machinery merger)","PIR-06","positive",0.48,"improving","none",4,"rev13 +0.45 -> rev14 +0.48. 171500 Metro BM FULL TEXT recovered: 'PRN N9: BN-PN gabung jentera, tekad rampas NS' (18:29, Hamzah). Attendees Takiyuddin, Kiandee (despite suspension), Mazalan, candidates Razali/Asna/Dr Rafie. Reinforced by joint-manifesto + kongsi-pentas. PIR-06 cooperation DEEPENS to 4 stages.")
a("BN-PN joint manifesto (manifesto bersepadu)","PIR-06","positive",0.48,"improving","none",5,"rev13 +0.45 -> rev14 +0.48. 171500 Metro BM FULL TEXT 'PN-BN bakal tampil manifesto bersepadu' (20:22, KOMPAS). Annuar confirms PN working committee. Attendees Samsuri, Takiyuddin, Sanusi, Wan Saiful. Two manifestos (joint + local ikrar). MAJOR formalization. Tension with 'sasar bentuk kerajaan' Bersatu solo bid.")
a("Wawasan admitted to PN","PIR-06","neutral",-0.15,"stable","priority",3,"Director-flagged. FMT 22 Jun: Hamzah's Wawasan + Pejuang admitted into PN. Coalition structure: PN = PAS+Gerakan+MIPP+Wawasan; Bersatu SOLO (24 seats). Resolves 'mystery of 11 PN seats' (Ridzuan=Wawasan in Gemas).")
a("PDM Klawang shutdown/reopen","PIR-06","negative",-0.22,"declining","priority",3,"rev13 -0.20 -> rev14 -0.22. FMT BM 19 Jul 15:33 (Jalaluddin) + FMT EN 17:02: BN PDM in Klawang (N.28) SHUT DOWN in protest over seat ceded to PN's Danni Rais. Jalaluddin expects reopen 1-2 days. Grassroots-level BN-PN friction. Monitor reopen.")
# NEW PIR-06 entities
a("Mohamed Khaled Nordin","PIR-06","negative",-0.30,"declining","priority",4,"NEW. Umno VP / Defence Minister / MP Kota Tinggi. 4-publisher (NST+BH+Metro+FMT, 23:49-00:16 MYT 19-20 Jul). Anti-Bersatu electoral-elimination: 'Pastikan Bersatu di NS KO habis-habis' / 'make sure Bersatu gets knocked out'. Frames Bersatu 'ditubuhkan nak ganti UMNO' + 'kacau daun'. Pro BN-PN: 'persefahaman BN-PN beri kelebihan vs Johor'; 'gelombang Melayu ke BN'. Dismisses AMK resign-call. Spoke at Johol BN machinery launch. Rhetorical escalation; NOT formal PN-MT action. [PRIORITY].")
a("Hassan Karim","PIR-06","neutral",-0.10,"stable","none",1,"NEW. PKR MP Pasir Gudang. Intra-PH dissent (FMT BM 15:00 MYT). Says BN-PN cooperation is 'normal'; PH shouldn't complain; recalls PH's own post-PRU2008 strategy to topple BN. Pushes back against AMH resign-demand. PKR old guard vs PH Youth. Adds nuance to resign-narrative.")
a("Bersatu KO habis (electoral-elimination call)","PIR-06","negative",-0.55,"declining","priority",4,"NEW. Khaled Nordin 4-publisher (NST+BH+Metro+FMT 23:49-00:16 MYT). 'Pastikan BERSATU di NS KO habis' — urges voters reject Bersatu so all 24 lose deposits, paving way for BN straight fights next PRU. Director PIR-06 keywords 'keluar/pecat/tarik diri' = coalition-membership actions; THIS is electoral-elimination rhetoric by a BN (not PN) leader — adjacent but NOT formal PN-MT expulsion/withdrawal. [PRIORITY] not [CRITICAL].")
a("gelombang Melayu ke BN (Malay wave to BN)","PIR-06","positive",0.35,"improving","none",2,"NEW. Khaled Nordin (BH+Metro 00:13-00:56 MYT 20 Jul). Johor PRN result triggers 'gelombang Melayu' supporting BN in NS. 'Orang Melayu dah ada kesedaran mahu sokong BN.' Pairs with 'persefahaman BN-PN beri kelebihan'. Pro-BN Malay-unity narrative.")
a("PN kongsi pentas dengan BN (joint ceramah)","PIR-06","positive",0.40,"improving","none",1,"NEW. Utusan 12:13 MYT (headline only): 'PN benarkan pimpinan kongsi pentas dengan BN'. 4TH stage of BN-PN cooperation formalization trajectory: (1) seat-swap, (2) gabung-jentera (18:29), (3) manifesto bersepadu (20:22), (4) kongsi pentas. Watch whether 24 Jul BN manifesto launch becomes JOINT BN-PN event.")
a("Khaled dismisses AMK resign-call","PIR-06","neutral",-0.15,"stable","none",1,"NEW. Khaled (Awani 23:36 MYT) dismisses AMK challenge to Akmal: 'Tak payahlah dia nak suruh... dia cakap sajalah dengan Ketua Parti dia.' Reinforces 'menteri hak mutlak PM'. New Khaled-vs-AMK/AMH friction axis.")

# ===== PIR-16 =====
a("Bersatu exit from PN imminent? (mkini SNAPSHOT)","PIR-16","negative",-0.55,"stable","priority",3,"Carried rev13. 153300+171500: gnews 'bersatu exit pn'=0 + 'sasar kerajaan negeri'=0 (12th consecutive cycle). No hard-news corroboration of THAT exact framing. mkini SNAPSHOT (18 Jul 18:00) remains lone viral-tier item. [CRITICAL] threshold NOT CROSSED — [PRIORITY] only. Substantive exit signals (lebih-hebat -0.78, sasar -0.80) ARE [CRITICAL] hard-news, scored separately.")
a("Bersatu in disarray (Wan Saiful kacau daun + Kiandee + resignations + Khaled)","PIR-16","negative",-0.70,"declining","priority",5,"rev13 -0.65 -> rev14 -0.70. UPGRADED: Khaled Nordin 4-publisher 'kacau daun' + 'KO habis' hard-news (FIRST BN-VP-level corroboration) + Wan Saiful kacau daun (Metro 16:31) + Kiandee quorum + MPT resignations + analyst wipeout consensus + Hamzah rebuke. Director-listed 'Bersatu in disarray' entity, deepening.")
a("Anthony Loke","PIR-16","positive",0.52,"improving","none",9,"rev13 +0.50 -> rev14 +0.52. NEW 171500: 'campaign on policies not personal attacks' (3-publisher) + 'PH sasar 23 kerusi' safe-majority (5-publisher) + 'not campaigning in Rantau' (unity-govt restraint) + rebuts 'neglected Chennah' (transport-minister advantage). 'MCA biggest loser' taunt persists. Active/on-offense Day-1. DAP leadership show of force.")
a("Wee Ka Siong","PIR-16","neutral",-0.10,"stable","none",3,"Awani: 'kerjasama BN-PN bukan perkara besar untuk kekal PN.' Carrier of 'not a merger' containment. Defensive-neutral. No escalation beyond this.")
a("Mah Hang Soon","PIR-16","neutral",-0.10,"stable","priority",0,"WATCH entity (Director PIR-16 list); no statement/response to Loke 'biggest loser' taunt across 10 cycles. Only Wee's 'not a coalition' defense surfaced.")
a("MCA biggest loser (Loke) + MCA rebuttal trajectory","PIR-16","negative",-0.52,"declining","priority",6,"rev13 -0.50 -> rev14 -0.52. Loke mocks MCA 'generosity' ceding 3 seats. MCA rebuttal = Wee containment + Saw Yee Fung told to skip NS (internal, viral 9,100 likes) + Chong Sin Woon WhatsApp. Rebuttal = CONTAINMENT not counter-attack -> MCA defensive, deepening.")
a("Bersatu kacau daun (Wan Saiful + Khaled)","PIR-16","negative",-0.58,"declining","priority",4,"rev13 -0.50 -> rev14 -0.58 (ESCALATED). UPGRADED 171500: Khaled Nordin (Umno VP/Defence Minister) attributes 'Bersatu hanya kacau daun' in hard-news 4-publisher (FMT BM+BH BM+Metro BM+NST EN, 23:49-00:16 MYT) — FIRST hard-news corroboration of this PIR-16 narrative keyword by BN-VP-level voice. Plus Wan Saiful (Metro 19 Jul 16:31). Challenges 'penyatuan undi Melayu'. [PRIORITY] not [CRITICAL] (CRITICAL trigger = 'Bersatu exit imminent?' or 'sasar bentuk kerajaan' hard-news — neither newly crossed).")
a("Wan Saiful Wan Jan","PIR-16","negative",-0.30,"declining","priority",3,"Sacked Bersatu, now Wawasan VP. 'Bersatu messing things up' (The Vibes 19 Jul). 'Bersatu kacau daun' (Metro 16:31). Present at joint-manifesto meeting. Disarray-narrative amplification.")
a("Albert Tei","PIR-16","neutral",-0.50,"stable","priority",0,"WATCH entity (Director PIR-16 list); 0 fresh items across 10 cycles. Linked to 'barking dogs' narrative.")
a("barking dogs","PIR-16","neutral",-0.55,"stable","priority",0,"WATCH entity (Director PIR-16 list); gnews query returned 0 items across cycles. Retained as watch-entity.")
a("majoriti mudah (BN confidence)","PIR-16","neutral",0.0,"stable","none",0,"Director PIR-16 monitor. NOT directly quoted this cycle. Latent — watch for BN manifesto launch 24 Jul. Loke 'PH sasar 23 kerusi' implicitly says 19 'majoriti mudah' is NOT enough.")
a("Muhyiddin graft trial","PIR-16","negative",-0.55,"stable","priority",2,"Director PIR-16 monitor. Court of Appeal (18 Jun) upheld High Court finding Muhyiddin defamed Lim Guan Eng re: Yayasan Albukhary. Backdrop to 'lebih hebat' PRU16 positioning.")
a("sole opposition (Muhyiddin lone credible opposition)","PIR-16","negative",-0.50,"declining","none",4,"rev13 -0.50 stable. 153300 corroborated by Muhyiddin 'Bersatu now sole opposition party' (The Vibes 18 Jul). Bersatu framed as sole credible Malay opposition; PN's BN arrangement means PN 'indirectly supports government'. Underpins 'lebih hebat' post-PRN coalition rationale.")
a("MB after PRN (PN concedes MB to BN)","PIR-16","neutral",0.15,"improving","none",4,"rev13 +0.15. Jalaluddin (FMT 15:27): 'PN agrees NS MB post for BN if pact wins'. MB-stock: Jalaluddin, Tok Mat, Sufian Maradzi. 171500: Tok Mat 'Saya sedia letak jawatan' 5th outlet (Metro BM 19:42) — 5-publisher total. Reinforced by joint-manifesto. NOTE: DIRECTLY CONTRADICTED by 'sasar bentuk kerajaan negeri' (Bersatu solo bid).")
a("penyatuan undi Melayu","PIR-16","neutral",0.15,"declining","none",7,"rev13 +0.20 -> rev14 +0.15 (further declining). CHALLENGED: Bersatu 24 solo + 8 overlaps fragment Malay vote (Wan Saiful 'kacau daun' + Khaled 'KO habis'). Proponents (Hadi, Tok Mat, Khaled 'gelombang Melayu') still vocal, but objective coherence under material pressure. Joint manifesto may consolidate somewhat.")
a("makmal politik PRU16 framing","PIR-16","neutral",0.25,"improving","none",5,"Carried rev13. Hadi 'bukan retorik' + Zahid 'prestasi BN-PN penutu PRU16' + Zaharuddin Sani 'makmal politik' + Zan Azlee. NS PRN as political laboratory for PRU16. Consolidating with more carriers + Annuar joint-manifesto + kongsi-pentas.")
a("Malay-Muslim unity with non-extreme partners (Hadi)","PIR-16","positive",0.30,"improving","none",2,"Awani: PAS+UMNO+MCA+MIC+DHPP 'non-extreme' formula; extend to Sabah/Sarawak. Constructive coalition-building.")
a("Act now or lose chance forever (Tok Mat)","PIR-16","positive",0.40,"improving","none",2,"Tok Mat existential Malay-future: 'miss the boat... children become mere traders in own country.' Energizes BN base. Reinforced by NST 21:03 'ready to resign' compliance.")
a("Ali Baba Bujang Lapok / 40 thieves (Anwar counter)","PIR-16","positive",0.35,"improving","none",2,"Anwar (NST 12:21): '40 thieves were also united.' Multi-ethnic counter mocking BN-PN cooperation as farcical.")
a("Mature campaign / kempen matang","PIR-16","positive",0.40,"improving","none",2,"Voters urge mature campaign; Bakri Sawir (Klawang) calls for tertib. 19 permits approved. Counter to provocation-heavy campaigning.")
a("Melaka PH-BN fracture / DAP withdrawal","PIR-16","negative",-0.42,"stable","priority",8,"Carried rev13. DAP withdrew from Melaka state govt; Ab Rauf+Adly still seated. Anwar 'not briefed'. Opposition weaponises as 'DAP coalition-intolerant'. Stable; visibility shifting to NS Day-1.")
a("Anwar 'not briefed' (Melaka DAP fallout)","PIR-16","negative",-0.30,"stable","priority",1,"Malay Mail (15 Jul): Anwar yet to receive briefing. Feeds DAP-coalition-intolerant counter-narrative.")
a("DAP coalition-intolerant (Hadi frame)","PIR-16","negative",-0.45,"declining","priority",3,"Hadi: reject 'unnatural Malay groups with DAP' — frames DAP as threat in 13 non-Malay DUNs. Counter: Lim Kit Siang rejects Islamophobia; Madani reforms (Teo). Frame intensifying; counter emerging.")
a("Lim Kit Siang","PIR-16","positive",0.30,"stable","none",1,"Awani: 'tolak Islamophobia, gelombang hijau istilah dicipta Hadi.' Counter-narrative to DAP-coalition-intolerant frame.")
a("derhaka friction (Pertang)","PIR-16","negative",-0.20,"declining","priority",4,"Carried rev13. NST 15:36 + Metro 15:53 + BH 15:02 'Tak masuk akal tuduh saya derhaka'. PH labels Jalaluddin MB-withdrawal 'derhaka'; Jalaluddin rebuts (treachery = to ruler/Undang, NOT to MB). Onn Hafiz 'DNA UMNO bukan penderhaka'. Director rule: 'derhaka' at Pertang = [PRIORITY].")
a("Onn Hafiz","PIR-16","positive",0.25,"stable","none",1,"Johor MB; 'DNA UMNO bukan penderhaka' (BH 14:47). Counters 'derhaka' framing. Johor formula (~8% GDP) as BN success model.")
a("AMH resign-call (PH Youth joint statement)","PIR-16","negative",-0.40,"stable","priority",5,"Carried rev13. AMH (Awani 10:43, 4-outlet) calls BN Ministers+Deputies to resign. 153300+171500: Hassan Karim (PKR MP) pushback 'Tak pelik... PH juga selepas PRU 2008 mengatur strategi jatuhkan BN' + Khaled dismisses AMK. Intra-PH dissent added. Resign-narrative trigger.")
a("resign-to-attack unity partners (federal-state firewall)","PIR-16","positive",0.35,"improving","none",4,"Carried rev13. Anwar directive (NST+FMT/BH+Awani 17:30, 3-outlet): ministers must resign if attacking unity-govt allies. Tok Mat accepted (4-outlet 19:28-21:03 FRESHEST NST 21:03). 171500: Khaled 'menteri hak mutlak PM' + Akmal NST conditional. Firewall hardening.")
a("Akmal counter-escalation (Umno Youth, Nga resign too)","PIR-16","negative",-0.35,"stable","priority",6,"rev13 -0.35. 171500 NST full text (23:59): 'the day Nga submits his, I will submit mine.' Context: Nga allegedly pledged to resign if BN won Johor (Newswav+MSN 17 Jul) — Akmal calling out pre-existing pledge, not just deflecting. Resign-narrative now BOTH sides.")
a("Akmal Noradzmi","PIR-16","negative",-0.35,"stable","priority",5,"Umno Youth chief, Melaka exco. Counter-escalation to AMH: 'I'll quit Melaka exco if Nga resigns as minister' (FMT EN 12:40 + BM 11:44). Attacks PH Youth resign-call as 'janggal dan keterlaluan'.")
a("Nga Kor Meng","PIR-16","neutral",-0.10,"stable","priority",2,"DAP vice-chairman, Housing Minister. TARGET of Akmal counter-demand. 171500: Nga resignation pledge context (allegedly pledged to resign if BN won Johor). DAP/Nga response NOT yet detected.")
a("Madani reforms continuity (Teo Nie Ching)","PIR-16","positive",0.42,"improving","none",2,"rev13 +0.40 -> rev14 +0.42. 153300 corroborated by BH BM (22:35) — now 2-publisher (NST EN 22:07 + BH BM 22:35). Teo: PH mandate to continue Madani reforms; record highs trade/tourism/reserves; 10A SPM matriculation; DAP 'undeterred' after Johor. PH counter to BN-PN stability/Johor formula.")
a("Teo Nie Ching","PIR-16","positive",0.42,"improving","none",2,"DAP Women's chief, Kulai MP. PH dinner (22:07 FRESHEST). 'Madani reforms continuity' pitch. Present: Loke, Gobind, Cha Kee Chin. DAP 'undeterred' — defeats = reflection, not abandoning principles.")
a("Gobind Singh Deo","PIR-16","neutral",0.15,"stable","none",1,"DAP national chairman; PH dinner (22:07) with Teo+Loke+Cha — top DAP leadership showing force in Seremban late evening.")
a("Cha Kee Chin","PIR-16","neutral",0.10,"stable","none",2,"NS DAP secretary; PH dinner (22:07) + PH manifesto launch coverage (NST 19:50).")
a("Ammar Atan","PIR-16","neutral",-0.20,"stable","none",1,"AMH info chief / AMANAH Youth deputy; co-signatory AMH joint statement.")
a("Ho Chi Yang","PIR-16","neutral",-0.20,"stable","none",1,"DAPSY national publicity secretary; co-signatory AMH joint statement.")
a("Danish Hairudin","PIR-16","neutral",-0.20,"stable","none",1,"PKR Youth info chief; co-signatory AMH joint statement.")
a("Syazana Nasir","PIR-16","neutral",-0.20,"stable","none",1,"WARDA communications bureau director; co-signatory AMH joint statement.")
a("Saw Yee Fung","PIR-16","negative",-0.22,"declining","priority",2,"rev13 -0.20 -> rev14 -0.22. 171500 TRP: MCA Youth sec-gen publicly questioned BN-PAS cooperation, contradicting what she told Johor voters. Chong Sin Woon WhatsApp 'you don't need to come' (4:58 PM); Saw screenshot+posted publicly (9,100 likes). FIRST concrete MCA-leader pushback vs BN-PN/PAS. Viral amplifier = [PRIORITY].")
a("Chong Sin Woon","PIR-16","neutral",-0.12,"stable","none",2,"MCA sec-gen; sent WhatsApp to Saw Yee Fung instructing skip NS campaign. Later clarified party decision per BN electoral arrangement. Internal MCA discipline enforcement.")
a("'Umno dangerous dance with PAS' (FMT opinion)","PIR-16","negative",-0.60,"stable","priority",1,"FMT FULL-TEXT opinion: 'By quietly opening the side door for PAS in NS, Umno is validating the very force designed to replace it.' Cites Amanat Hadi (1981). Warns urban non-Malay alienation. Highest-risk viral-amplifier opinion.")
a("Amanat Hadi (1981, historical reference)","PIR-16","negative",-0.40,"stable","none",1,"1981 Amanat Hadi labelled Umno supporters 'infidels' — cited in FMT 'dangerous dance' opinion.")
a("'charade to deceive the Malays' (Muhyiddin counter)","PIR-16","negative",-0.45,"stable","none",2,"Muhyiddin: accuses Umno/BN of using 'Malay unity' to win Malay voters — 'charade to deceive the eyes of the Malays.' Claims Bersatu 'free of all this charade'. Direct counter to Tok Mat/Hadi Malay-unity framing.")
a("Syahir Che Sulaiman","PIR-16","neutral",0.10,"stable","none",1,"PAS Bachok MP; rebuts PH Youth resign-demand; 'ujian formula' framing of PN-BN cooperation; 'Confidence in Madani Govt eroding'.")
a("Lau Zhe Wei (IIUM analyst)","PIR-16","negative",-0.40,"declining","priority",2,"Advises Bersatu quit PN + take Gerakan/MIPP. MCA benefits from BN-PAS alliance (Johor MCA doubled to 8).")
a("Azeem Fazwan (USM analyst)","PIR-16","negative",-0.55,"declining","priority",1,"Expects Bersatu wiped out in NS — 'in no position to win seats going solo.' Lacks strong political base.")
a("Azmil Tayeb (USM analyst)","PIR-16","negative",-0.50,"declining","priority",1,"Bersatu problems run deeper than PAS issues; hasn't distinguished itself from Umno/PAS. 'All people see is infighting.'")
a("Ahmad Zaharuddin Sani (analyst)","PIR-16","neutral",0.15,"stable","none",1,"Carrier of 'makmal politik' framing. NS as PRU16 indicator.")
a("Azmi Hassan (analyst)","PIR-16","neutral",0.10,"stable","none",1,"Johor PAS-Umno success motivates NS PN-BN model.")
a("Zan Azlee (commentator)","PIR-16","neutral",0.10,"stable","none",1,"Frames state elections as bellwether — reinforces makmal-politik PRU16 framing.")
a("Johor formula / stability","PIR-16","positive",0.25,"stable","none",1,"BN pitch: Johor as model of stability/2/3 majority under BN-PN cooperation; extrapolated to NS. Onn Hafiz counters 'derhaka' framing.")
a("Indian community stability kingmaker","PIR-16","neutral",0.15,"stable","none",1,"Anbumani Balan (BH 18:01): Indian community should choose long-term stability. Relevant to N.10 Nilai (21.9% Indian) + N.33 Sri Tanjung (28.35% Indian).")
a("Anbumani Balan","PIR-16","neutral",0.10,"stable","none",1,"Political analyst; pitches stability to Indian voters; frames Indian votes as 'determining who forms state govt'.")
a("ujian formula (Syahir PAS)","PIR-16","neutral",0.0,"stable","none",1,"Syahir: PN-BN cooperation still at 'ujian formula' (testing-formula) stage, post-PRN undecided. Frames NS PRN as makmal-politik experiment. 'Confidence in Madani Govt eroding'.")
a("Undi Melayu merosot (PH strategy shift)","PIR-16","neutral",-0.20,"stable","none",1,"Analyst notes declining Malay support for PH — drives PH strategy to consolidate non-Malay (esp. Indian) vote in mixed seats. Connects to Indian-electorate kingmaker.")
a("Rafizi Ramli","PIR-16","neutral",-0.20,"stable","none",1,"'Kemelut PRN N9 zahir tanda awal kesan luar jangka kepada UMNO' — NS friction as early signal of unexpected fallout for UMNO.")
a("Fuziah Salleh","PIR-07","neutral",0.20,"stable","none",1,"PKR sec-gen; 'gadai kepercayaan rakyat jika tidak terima keputusan PRN' — warns all parties must accept NS PRN results. Positive process signal.")
a("Saarani","PIR-16","neutral",0.10,"stable","none",1,"Perak MB; Anwar National Month launch attendee. 'DAP reps pullout in Melaka won't affect Perak unity govt ties'.")
a("Ab Rauf","PIR-16","neutral",-0.10,"stable","none",1,"Melaka CM; 'DAP reps abrupt exit shuts door on negotiations'; 171500 rejected Akmal's Jan resignation, allowing Akmal to remain — context for Akmal conditional.")
a("Adly","PIR-16","neutral",0.10,"stable","none",1,"Amanah's Adly; maintains support for Melaka govt after DAP withdrawal — Amanah stays with govt bloc.")
# NEW PIR-16 entities
a("campaign on policies not personal attacks (Loke)","PIR-16","positive",0.40,"improving","none",3,"NEW. Loke (NST+BH+Metro 23:51-00:06 MYT): backs Anwar clean-campaign call; 'kempen patut tumpu tawaran, bukan serang peribadi.' Won't attack any Cabinet minister — 'they are my colleagues... we meet every week at Cabinet.' Counter to 'derhaka'/personal-attack narrative.")
a("Loke not campaigning in Rantau (unity-govt harmony)","PIR-16","positive",0.30,"stable","none",3,"NEW. Loke (NST+BH+Metro): chose NOT to campaign in Rantau (Tok Mat's seat) to 'menjaga keharmonian dalam Kerajaan Perpaduan.' Focuses on Chennah + DAP seats + helps Aminuddin in Linggi. Notable intra-unity-govt restraint — PH leader voluntarily ceding a battleground to a BN partner.")
a("PH sasar 23 kerusi (safe majority / 8123)","PIR-16","neutral",0.25,"improving","priority",5,"NEW. Loke (5-publisher NST+FMT EN+FMT BM+BH BM+Metro BM, 16:01-00:21 MYT 19-20 Jul). PH targets 23 of 36 for 'safe' majority. Math: 17 current; 18=tie; 19=simple 'apa sahaja boleh berlaku'; 23=safe. '8123'=Aug 1, target 23. Frames 2026 crisis: 14 Umno ADUN withdrew support + 5 PN backdoor attempt. Defends Aminuddin. Director 'majoriti mudah' adjacent — Loke says 19 'majoriti mudah' NOT enough. [PRIORITY PIR-16] NOT [CRITICAL] (PH-attributed, per Director rule only Bersatu-attributed 'sasar' = CRITICAL).")
a("MCA told her to stay home (Saw Yee Fung vs Chong Sin Woon)","PIR-16","negative",-0.30,"declining","priority",2,"NEW. TRP (17-19 Jul): Saw Yee Fung publicly questioned BN-PAS cooperation, contradicting her Johor voter messaging. Chong Sin Woon WhatsApp '森州州选妳不需要来' (4:58 PM); Saw screenshot posted publicly (9,100 likes). FIRST concrete MCA-leader pushback vs BN-PN/PAS. Top leadership (Wee/Mah) still silent. Viral amplifier = [PRIORITY].")
a("Teng Chang Khim","PIR-16","neutral",-0.10,"stable","none",1,"NEW. DAP leader (Selangor Speaker / senior exco). Challenged Akmal to follow through on earlier resignation pledge (NST 23:59). Triggered Akmal's conditional 'I'll resign if Nga quits' counter.")
a("Nga resignation pledge (Johor precondition)","PIR-16","neutral",-0.10,"stable","none",2,"NEW context. Nga Kor Ming allegedly pledged to resign if BN won Johor (Newswav+MSN 17 Jul) — pledge predates NS PRN. Akmal's counter is calling out pre-existing pledge. A DAP leader says Nga's remarks were misinterpreted. Enriches resign-narrative chain.")
a("Tuanku Muhriz Tuanku Munawir","PIR-16","neutral",0.0,"stable","none",1,"NEW. Yang di-Pertuan Besar Negeri Sembilan. April 19 royal/political crisis context (Loke speech NST+FMT 16:03): four undangs claimed Tuanku Muhriz had been removed — sparking crisis leading to 14 Umno ADUN withdrawing support for MB Aminuddin and the NS PRN.")
a("April 19 royal crisis (4 undangs claim Tuanku Muhriz removed)","PIR-16","neutral",-0.10,"stable","priority",1,"NEW. April 19 2026: NS's four undangs (traditional chieftains) claimed Tuanku Muhriz removed as Yang di-Pertuan Besar — sparking royal+political crisis. Resulted in all 14 Umno ADUN withdrawing support for MB Aminuddin + 5 PN ADUN attempting 'backdoor government.' THE TRIGGER for Aug 1 NS PRN. Loke uses this to justify PH's 'safe majority 23' target. [PRIORITY] — central to understanding the election's origin.")
a("14 Umno ADUN withdrew support + 5 PN backdoor attempt","PIR-16","negative",-0.30,"stable","priority",1,"NEW. Loke speech (NST+FMT 16:03): 'Fourteen Umno assemblymen withdrew their support (for the MB) and joined forces with five PN assemblymen to attempt to form a backdoor government.' PH's political-crisis framing to justify fresh/stable mandate. Note: some of these 14 Umno ADUN are now BN candidates. [PRIORITY] — core PH campaign narrative.")

# ===== PIR-07 =====
a("Anwar Ibrahim (PM, coalition manager)","PIR-07","positive",0.45,"improving","none",6,"Carried rev13. 'resign if you want to attack unity partners' directive (Zahid+Fadillah, 3-outlet). 'Ali Baba 40 thieves were also united' multi-ethnic counter (NST 12:21). Managing coalition discipline (AMH->Anwar->Tok Mat->Akmal). Positive for coalition coherence.")
a("PH (Pakatan Harapan)","PIR-07","positive",0.42,"improving","none",5,"rev13 +0.40 -> rev14 +0.42. Incumbent NS govt. 171500: Loke 'PH sasar 23 kerusi' safe-majority framing + 'campaign on policies' + 'not in Rantau' + Madani reforms (Teo). Manifesto launch 20 Jul centred on 'kesinambungan Tok Min'. 889,490 voters; polling 1 Aug.")
a("PKR","PIR-07","neutral",0.10,"stable","none",1,"PH component (Aminuddin, Fuziah's party). Part of PH incumbent administration. 171500: Hassan Karim (PKR MP) intra-PH dissent adds nuance.")
a("Aminuddin Harun (PH incumbent MB, N.32 Linggi)","PIR-07","positive",0.62,"stable","priority",10,"Carried rev13. NO >20% drop; stable. 171500: 'lebih selesa berkempen dalam kumpulan kecil' (Metro 16:47) — caretaker MB status gives no advantage; Linggi traditionally BN stronghold. Loke defends: 'done nothing wrong, not corrupt, not arrogant.' 3-cornered Linggi split structurally helps PH incumbent. PH manifesto centres on 'kesinambungan Tok Min'. Priority-watch (director monitor), no critical.")
a("N.32 Linggi (Aminuddin MB move + BN manifesto 24 Jul)","PIR-07","positive",0.35,"stable","none",7,"Aminuddin (PH) vs BN Mohd Faizal Ramli vs Bersatu Zamri Md Said. 3-cornered split helps PH incumbent. 171500: Aminuddin small-group campaign; acknowledges caretaker status no advantage; positive Indian voter reception at Pekan Pasir Panjang. BN manifesto launch 24 Jul at DUN Linggi = upcoming pressure event (watch — JOINT BN-PN?).")
a("'fleeing Sikamat' narrative (directed at Aminuddin)","PIR-07","negative",-0.45,"stable","priority",6,"Carried rev13. Persists NOT intensifying. 171500: Aminuddin 'lebih selesa berkempen dalam kumpulan kecil' at Linggi (Metro 16:47) — acknowledges caretaker no advantage; 'pindah kawasa' framing. 'fled' frame not gaining traction.")
a("no easy path for political top guns","PIR-07","neutral",-0.10,"stable","priority",1,"Director [PRIORITY] flag. NST (18 Jul): no easy path for NS political top guns. Nazri Kassim (PH Ampangan) 'tidak memandang mudah' embodies this. Battle 'tougher than Johor' (The Vibes).")
a("N.13 Sikamat (Nor Azman vs Tun Faisal, 3-corner)","PIR-07","positive",0.40,"stable","none",5,"Nor Azman (PH, Aminuddin's pol-sec) vs Tun Faisal (Bersatu, RoS-complaint figure) vs Razali (Wawasan/PN). 3-cornered split helps PH. 'fleeing Sikamat' anchored here. Loke criticised BN candidate. No new negative.")
a("Nor Azman Mohamad (PH N.13 Sikamat)","PIR-07","neutral",0.10,"stable","none",2,"Aminuddin's political secretary; defending seat Aminuddin vacated for Linggi. Slightly positive PH defence.")
a("Razali Abu Samah (PN/Wawasan N.13 Sikamat)","PIR-07","neutral",0.0,"stable","none",2,"PN/Wawasan candidate N.13 Sikamat (Tier-4); Hamzah met him at gabung-jentera (NST 19:49).")
a("N.28 Klawang (PDM shutdown + cousins contest)","PIR-07","positive",0.25,"declining","none",5,"rev13 +0.30 -> rev14 +0.25 (declining). PDM Klawang shutdown (FMT 19 Jul) = grassroots-friction signal; Jalaluddin expects reopen 1-2 days. Cousins contest (Bakri PH vs Danni PN vs Adib Bersatu) remains positive/mature (Awani 19 Jul 12:11). Net: seat declines on PDM friction; incumbent Bakri unaffected. No incumbent drop >20%.")
a("Bakri Sawir (PH Klawang incumbent)","PIR-07","positive",0.45,"stable","none",2,"Confident Day-1 posture; 'brotherly fight' with cousin Danni Rais; mature-campaign framing. Took down warned flags. Positive incumbent signal, no drop. PDM shutdown concerns BN machinery, not Bakri.")
a("Danni Rais (PN Klawang, Bakri's cousin)","PIR-07","neutral",0.10,"stable","none",2,"PN challenger; Bakri's cousin; peaceful campaign. 'Dua sepupu bertembung' marquee Day-1 storyline. Neutral challenger posture.")
a("Muhammad Adib Musa (Bersatu Klawang)","PIR-07","neutral",-0.15,"stable","none",1,"Bersatu third-force splitter in 3-cornered Klawang. Splits opposition vote; structurally helps PH incumbent.")
a("Mohamad Hasan / Tok Mat (BN Rantau)","PIR-07","positive",0.62,"improving","none",8,"rev13 +0.62. 171500: 5th outlet (Metro BM 19:42) joins 4-outlet 'Saya sedia letak jawatan jika ada arahan PM' (5-publisher total). 'act now or lose chance forever' existential Malay-future. 'no intention to attack central leaders.' MB-stock candidate. Heavyweight 2-cornered vs PH. Stable, improving on resign-to-attack compliance. 171500: Loke chose NOT to campaign in Rantau (unity-govt restraint) — implicitly eases pressure on Tok Mat.")
a("Rantau (Tok Mat seat, straight fight)","PIR-07","positive",0.50,"stable","none",4,"Tok Mat (2023 maj 10,280) vs PH Dr Azizul Hakim Mahdi. Straight fight. Connected to resign-to-attack federal-state firewall. 171500: Loke explicitly not campaigning here to preserve unity-govt harmony — a PH leader voluntarily ceding a battleground. BN heavyweight. Day-1 dispatch.")
a("Dr Azizul Hakim Mahdi (PKR/PH Rantau)","PIR-07","neutral",0.10,"stable","none",1,"PKR/PH candidate Rantau (straight fight vs Tok Mat). PH newcomer challenging Tok Mat on home turf.")
a("Pertang (derhaka friction, Jalaluddin)","PIR-07","neutral",-0.20,"declining","priority",5,"Carried rev13. 3-cornered: BN Jalaluddin (defends) vs 2 challengers. 'derhaka' friction corroborated (BH+NST+Metro). Jalaluddin rebuttal 'tak masuk akal... jangan spin, tanam kebencian.' Director rule: 'derhaka' at Pertang = [PRIORITY]. BN manifesto launch 24 Jul here (alongside Linggi).")
a("Jalaluddin Alias (NS Umno chief, BN Pertang)","PIR-07","neutral",0.05,"declining","priority",6,"Multi-role: (1) PN concedes MB to BN (FMT 15:27), (2) PDM Klawang shutdown (FMT 15:33), (3) 'derhaka' rebuttal (NST 15:36+BH 15:02+Metro 15:53), (4) MB-stock candidate, (5) 'yakin BN kekal pertahan Pertang' (Utusan 17:56), (6) thanks Perikatan (Malay Mail). Booed at Jelebu nomination. Under defector-framing pressure but strong rebuttal. Net slightly positive (MB-stock) but declining (friction).")
a("N.14 Ampangan (Nazri Kassim, defector-framing watch)","PIR-07","neutral",-0.15,"stable","priority",3,"Carried rev13. Director PIR-07 watch. 3-corner. Muhammad Nazri Kassim (PH incumbent, 'tidak memandang mudah' = Director [PRIORITY] 'not taking for granted') vs Dr Rafie (PN/Wawasan, Hamzah met him NST 19:49). Defector-framing ACTIVE NOT intensifying. Priority-watch per directive.")
a("Muhammad Nazri Kassim (PH N.14 Ampangan, Datuk)","PIR-07","neutral",0.10,"stable","priority",2,"PH candidate N.14 Ampangan (incumbent, Datuk); 'tidak memandang mudah' (not taking for granted) — Director [PRIORITY] flag. gerak kerja kempen perlu diperkemaskan.")
a("Dr Rafie Abd Malek (PN N.14 Ampangan)","PIR-07","neutral",0.05,"stable","none",2,"PN candidate N.14 Ampangan (Tier-4); Hamzah met him at gabung-jentera (NST 19:49). Wawasan president campaigning with PN Tier-4 candidate.")
a("N.27 Chembong (Zaifulbahri vs Danish Nazran)","PIR-07","positive",0.35,"stable","none",2,"Straight fight: Zaifulbahri Idris (BN, since 2008; 2023 maj 4,335) vs Danish Nazran Murad (PH). BN-PN cooperation removes 3-corner. BN incumbent edge.")
a("Zaifulbahri Idris (BN N.27 Chembong)","PIR-07","neutral",0.10,"stable","none",1,"BN candidate N.27 Chembong (since 2008; 2023 majority 4,335).")
a("Danish Nazran Murad (PH N.27 Chembong)","PIR-07","neutral",0.05,"stable","none",1,"PH candidate N.27 Chembong (straight fight vs BN incumbent).")
a("N.15 Juasseh","PIR-07","neutral",0.20,"stable","none",1,"Tier-4 priority seat. BN 'unfazed' by 3-cornered. Limited discrete coverage. BN confidence.")
a("N.20 Bembang","PIR-07","neutral",0.0,"stable","none",0,"Director-listed Tier-4 seat. Candidate detail NOT recovered; 'N.20 Bembang'<->'Bahau' mapping unconfirmed. Kept per director list.")
a("N.25 Labu (Maira anak jati, Bersatu)","PIR-07","neutral",0.10,"improving","none",2,"Carried rev13. Bersatu candidate Maira positions as anak jati (native son). PH Ahmad Faez focuses on Orang Asli development (NST 19:06). Candidate detail recovered -> +0.10 improving.")
a("Maira (Bersatu N.25 Labu candidate)","PIR-07","neutral",0.15,"stable","none",1,"Bersatu candidate N.25 Labu. 'Anak jati' native-son positioning. Director-listed Tier-4 seat candidate. (BH 15:47)")
a("Ahmad Faez (PH N.25 Labu, Orang Asli focus)","PIR-07","neutral",0.10,"stable","none",1,"PH candidate N.25 Labu (Tier-4); Orang Asli development among key focus (NST 19:06).")
a("N.10 Nilai (5-corner, 21.9% Indian)","PIR-07","neutral",-0.05,"stable","none",3,"5-corner fight; 21.9% Indian electorate. Berjasa+Loke's aide Arul Kumar in mix. High Indian-electorate battleground. 5-cornered high split-risk.")
a("J Arul Kumar (PH N.10 Nilai, Loke's aide)","PIR-07","neutral",0.10,"stable","none",1,"PH candidate N.10 Nilai (5-cornered); Loke's aide, 4th term since 2013; 2023 majority 10,889.")
a("Lai Chien Kong (BN/MCA N.10 Nilai)","PIR-07","neutral",-0.05,"stable","none",1,"BN (MCA) candidate N.10 Nilai (5-cornered).")
a("V Saravan Kumar (Bersatu N.10 Nilai)","PIR-07","neutral",-0.10,"stable","none",1,"Bersatu candidate N.10 Nilai (5-cornered).")
a("Zamani Ibrahim (Berjasa N.10 Nilai)","PIR-07","neutral",-0.15,"stable","none",1,"Berjasa candidate N.10 Nilai (5-cornered).")
a("Omar Isa (Indep N.10 Nilai)","PIR-07","neutral",-0.10,"stable","none",1,"Independent candidate N.10 Nilai (5-cornered).")
a("N.33 Sri Tanjung (5-corner, 28.35% Indian)","PIR-07","neutral",-0.15,"stable","none",3,"5-corner fight; 28.35% Indian (highest). Leevineshwaraan youngest candidate (23). High Indian-electorate battleground. 5-cornered highest split-risk.")
a("Dr G Rajasekaran (PH N.33 Sri Tanjung)","PIR-07","neutral",0.10,"stable","none",1,"PH candidate N.33 Sri Tanjung (5-cornered); 2nd term; 2023 majority 3,996.")
a("A Achutan (BN N.33 Sri Tanjung)","PIR-07","neutral",-0.05,"stable","none",1,"BN candidate N.33 Sri Tanjung (5-cornered).")
a("M Leevineshwaraan Murugan (Bersatu N.33, youngest)","PIR-07","neutral",-0.10,"stable","none",1,"Bersatu candidate N.33 Sri Tanjung (5-cornered); YOUNGEST NS PRN candidate (Awani 18 Jul 06:57); contrasts with Tok Mat 'antara paling otai'.")
a("A Saravanan (Indep N.33 Sri Tanjung)","PIR-07","neutral",-0.10,"stable","none",1,"Independent candidate N.33 Sri Tanjung (5-cornered); Datuk.")
a("Islah Wahyudi Sainudin (Indep N.33 Sri Tanjung)","PIR-07","neutral",-0.10,"stable","none",1,"Independent candidate N.33 Sri Tanjung (5-cornered).")
a("Chennah (Loke vs Siow straight fight, 47.8% Malay)","PIR-07","positive",0.35,"stable","none",3,"Carried rev13. Loke's incumbent seat (PH/DAP) — only MCA-DAP straight fight in NS. Siow Kong Choon (MCA) challenger. 47.8% Malay. Loke confident based on khidmat bakti since 2013. 171500: Loke rebuts 'neglected Chennah' — transport-minister status channelled more benefits (Kampung Madani). Marquee MCA-vs-DAP battleground.")
a("Chennah demographics risk (Loke LOSES if PRU15 repeats)","PIR-07","negative",-0.28,"stable","priority",2,"rev13 -0.30 -> rev14 -0.28 (slight ease). mkini 780075: 47.8% Malay (up from 44% in 2018), 6.3% Orang Asli, 42.6% Chinese, 2% Indian; PH vote DROPPED to 44% by PRU15; BN+PN combined 56% -> if PRU15 repeats, Loke LOSES. 171500: Loke rebuttal — transport-minister advantage + full-time team + Kampung Madani projects. Risk persists; counter emerging.")
a("Siow Kong Choon (MCA NS Youth, Chennah challenger)","PIR-16","neutral",0.05,"stable","none",2,"BN Chennah candidate directly challenging Loke. The lone MCA-DAP straight fight — symbolic 'biggest loser' test for MCA.")
a("Kota (3-corner, razor 135-vote margin)","PIR-07","neutral",-0.15,"stable","none",1,"3-corner contest. 2023 margin razor-thin at 135 votes. Suhaimi Aini (BN, 'never left Umno since 1959' stronghold) vs Allif Ibrahim (PH) vs Akmal Noradzmi Abd Rahim (Bersatu). HIGHEST-RISK marginal seat.")
a("Suhaimi Aini (BN Kota, 135-vote margin)","PIR-07","neutral",0.05,"stable","none",1,"BN candidate Kota (defends); 2023 majority only 135 votes (razor margin); 'never left Umno since 1959' — BN stronghold test; HIGHEST-RISK marginal.")
a("Allif Ibrahim (PH Kota)","PIR-07","neutral",0.05,"stable","none",1,"PH candidate Kota (3-cornered).")
a("Akmal Noradzmi Abd Rahim (Bersatu Kota)","PIR-07","neutral",-0.10,"stable","none",1,"Bersatu (solo-logo) candidate Kota (3-cornered); NOT to be confused with Umno Youth chief Akmal Noradzmi (Melaka exco) — different person, same name region.")
a("Gemas (Ridzuan Wawasan, BN ops rooms assist PN)","PIR-07","neutral",0.10,"stable","none",2,"STRAIGHT FIGHT (machinery-sharing seat); PKR Siti Aishah Seman (PH) vs Wawasan Ridzuan Ahmad (PN) — Bersatu-quit figure; BN gave way to PN; BN ops rooms open to assist PN. 'We do not want any sabotage.'")
a("Siti Aishah Seman (PKR/PH Gemas)","PIR-07","neutral",0.10,"stable","none",1,"PKR/PH candidate Gemas (straight fight vs Wawasan's Ridzuan Ahmad).")
a("Lenggeng (3-corner, Zool Amali defector)","PIR-07","neutral",0.0,"stable","none",2,"3-CORNERED; BN Mohd Asna Amin vs Amanah Zarinna Abu Zarin vs Bersatu Zool Amali Hussein (former Seremban Umno Youth chief — defector); 'shifting alliances'. Mohd Asna met Hamzah at gabung-jentera.")
a("Mohd Asna Amin (BN Lenggeng)","PIR-07","neutral",0.10,"stable","none",1,"BN candidate Lenggeng (3-cornered); met Hamzah at gabung-jentera (NST 19:49).")
a("Zarinna Abu Zarin (Amanah/PH Lenggeng)","PIR-07","neutral",0.05,"stable","none",1,"Amanah/PH candidate Lenggeng (3-cornered).")
a("Zool Amali Hussein (Bersatu Lenggeng, defector)","PIR-07","negative",-0.20,"stable","none",1,"Bersatu (solo-logo) candidate Lenggeng (3-cornered); former Seremban Umno Youth chief — DEFECTOR; 'shifting alliances' narrative embodiment.")
a("Rahang (4-corner, Tang Jay Son pecat)","PIR-07","neutral",-0.10,"stable","none",2,"4-CORNERED; PH Desmond Siau Meow Kong vs BN Yap Siok Moy vs Bersatu Tang Jay Son (expelled Gerakan) vs PSM T. Tharmaseelan.")
a("Desmond Siau Meow Kong (PH Rahang)","PIR-07","neutral",0.05,"stable","none",1,"PH candidate Rahang (4-cornered); one of 6 PH candidates at Loke's Pasar Besar Seremban walkabout.")
a("Yap Siok Moy (BN/MCA Rahang)","PIR-07","neutral",-0.05,"stable","none",1,"BN (MCA) candidate Rahang (4-cornered).")
a("T. Tharmaseelan (PSM Rahang)","PIR-07","neutral",-0.10,"stable","none",1,"PSM candidate Rahang (4-cornered).")
a("Tang Jay Son (Bersatu Rahang, pecat)","PIR-07","neutral",-0.15,"stable","priority",1,"Bersatu (solo-logo) candidate Rahang (4-cornered); EXPELLED secara serta-merta from Gerakan for contesting on Bersatu ticket (Awani 18 Jul 20:22) — [CRITICAL] 'pecat' enforcement; Bersatu attracting Gerakan defectors -> intra-PN friction.")
a("Lobak (DAP vs PAS, MCA ceded)","PIR-07","neutral",0.05,"stable","none",1,"STRAIGHT FIGHT (urban); DAP Chew Seh Yong vs PAS Dr P Kumar; one of 3 traditional MCA seats CEEDED to PN per BN-PN pact — Loke 'MCA biggest loser' taunt.")
a("Chew Seh Yong (DAP/PH Lobak)","PIR-07","neutral",0.15,"stable","none",1,"DAP/PH candidate Lobak (straight fight vs PAS); one of 6 PH candidates at Loke's walkabout.")
a("Dr P Kumar (PAS/PN Lobak)","PIR-07","neutral",-0.10,"stable","none",1,"PAS/PN candidate Lobak (straight fight vs DAP); MCA ceded this traditional seat to PN.")
a("Bukit Kepayang (DAP vs Gerakan)","PIR-07","neutral",0.05,"stable","none",1,"STRAIGHT FIGHT (urban); DAP incumbent Nicole Tan Lee Koon vs Gerakan Lee Boon Shian.")
a("Nicole Tan Lee Koon (DAP/PH Bukit Kepayang)","PIR-07","neutral",0.15,"stable","none",1,"DAP/PH incumbent Bukit Kepayang (straight fight vs Gerakan); one of 6 PH candidates at Loke's walkabout.")
a("Lee Boon Shian (Gerakan/BN Bukit Kepayang)","PIR-07","neutral",-0.05,"stable","none",1,"Gerakan/BN candidate Bukit Kepayang (straight fight vs DAP incumbent).")
a("Paroi (Amanah vs PAS)","PIR-07","neutral",0.0,"stable","none",1,"STRAIGHT FIGHT (urban); Amanah Ahmad Shahir Mohd Shah vs PAS Kamarol Ridzuan Mohd Zain.")
a("Ahmad Shahir Mohd Shah (Amanah/PH Paroi)","PIR-07","neutral",0.10,"stable","none",1,"Amanah/PH candidate Paroi (straight fight vs PAS).")
a("Kamarol Ridzuan Mohd Zain (PAS/PN Paroi)","PIR-07","neutral",-0.10,"stable","none",1,"PAS/PN candidate Paroi (straight fight vs Amanah).")
a("Lukut (DAP vs MIPP, MCA ceded)","PIR-07","neutral",0.05,"stable","none",1,"STRAIGHT FIGHT (coastal/Port Dickson); DAP incumbent Choo Ken Hwa vs MIPP Sathes Kumar Nilameham; one of 3 traditional MCA seats CEEDED to PN.")
a("Choo Ken Hwa (DAP/PH Lukut)","PIR-07","neutral",0.15,"stable","none",1,"DAP/PH incumbent Lukut (straight fight vs MIPP).")
a("Sathes Kumar Nilameham (MIPP/PN Lukut)","PIR-07","neutral",-0.05,"stable","none",1,"MIPP/PN candidate Lukut (straight fight vs DAP incumbent); MCA ceded to PN (MIPP).")
a("Bagan Pinang (Amanah vs PAS)","PIR-07","neutral",0.0,"stable","none",1,"STRAIGHT FIGHT (coastal/Port Dickson); Amanah Nasir Rahman vs PAS Abdul Fatah Zakaria.")
a("Nasir Rahman (Amanah/PH Bagan Pinang)","PIR-07","neutral",0.10,"stable","none",1,"Amanah/PH candidate Bagan Pinang (straight fight vs PAS).")
a("Abdul Fatah Zakaria (PAS/PN Bagan Pinang)","PIR-07","neutral",-0.10,"stable","none",1,"PAS/PN candidate Bagan Pinang (straight fight vs Amanah).")
a("Bahau (DAP vs MCA)","PIR-07","neutral",0.05,"stable","none",1,"STRAIGHT FIGHT; DAP incumbent Teo Kok Seong vs MCA Chong Fui Ming; BN hopes regain ground.")
a("Teo Kok Seong (DAP/PH Bahau)","PIR-07","neutral",0.15,"stable","none",1,"DAP/PH incumbent Bahau (straight fight vs MCA).")
a("Chong Fui Ming (MCA/BN Bahau)","PIR-07","neutral",-0.05,"stable","none",1,"MCA/BN candidate Bahau (straight fight vs DAP incumbent).")
a("Repah (DAP vs MCA)","PIR-07","neutral",0.05,"stable","none",1,"STRAIGHT FIGHT; DAP incumbent S. Veerapan vs MCA Koh Kim Swee.")
a("S Veerapan (DAP/PH Repah)","PIR-07","neutral",0.15,"stable","none",1,"DAP/PH incumbent Repah (straight fight vs MCA).")
a("Koh Kim Swee (MCA/BN Repah)","PIR-07","neutral",-0.05,"stable","none",1,"MCA/BN candidate Repah (straight fight vs DAP incumbent).")
a("Jeram Padang (4-corner, Sri Sanjeevan quorum-critic)","PIR-07","neutral",-0.05,"stable","none",2,"4-CORNERED; BN Mohd Zaidy Abdul Kadir vs PH G. Manivann vs Bersatu R. Sri Sanjeevan vs Dayana Dal (ASLI).")
a("Mohd Zaidy Abdul Kadir (BN Jeram Padang)","PIR-07","neutral",0.10,"stable","none",1,"BN candidate Jeram Padang (4-cornered).")
a("G Manivann (PH Jeram Padang)","PIR-07","neutral",0.05,"stable","none",1,"PH candidate Jeram Padang (4-cornered).")
a("R Sri Sanjeevan (Bersatu Jeram Padang, quorum-critic)","PIR-07","negative",-0.20,"stable","none",1,"Bersatu (solo-logo) candidate Jeram Padang (4-cornered); frames quorum issue as 'alasan sekat Bersatu bertanding PRN NS' (pretext to block Bersatu).")
a("Dayana Dal (ASLI Jeram Padang)","PIR-07","neutral",0.05,"stable","none",1,"Parti Orang Asli/ASLI candidate Jeram Padang (4-cornered).")
a("Temiang (PH Ho Weng Wah)","PIR-07","neutral",0.05,"stable","none",1,"MCA contests (one of 7 MCA seats); PH's Ho Weng Wah.")
a("Ho Weng Wah (DAP/PH Temiang)","PIR-07","neutral",0.10,"stable","none",1,"DAP/PH candidate Temiang; one of 6 PH candidates at Loke's walkabout.")
a("Mambau (DAP Lee Kai Yet, MCA ceded)","PIR-07","neutral",0.05,"stable","none",1,"MCA CEEDED to PN per BN-PN pact (one of 3 traditional seats); PH Lee Kai Yet; Tok Mat quoted in Mambau (FMT EN 19:57).")
a("Lee Kai Yet (DAP/PH Mambau)","PIR-07","neutral",0.10,"stable","none",1,"DAP/PH candidate Mambau; one of 6 PH candidates at Loke's walkabout.")
a("Seremban Jaya (PH S Mugunthan)","PIR-07","neutral",0.05,"stable","none",1,"PH's S. Mugunthan.")
a("S Mugunthan (DAP/PH Seremban Jaya)","PIR-07","neutral",0.10,"stable","none",1,"DAP/PH candidate Seremban Jaya; one of 6 PH candidates at Loke's walkabout.")
a("Seri Menanti (BN Sufian Maradzi, MB-stock)","PIR-07","neutral",0.10,"stable","none",1,"BN's Sufian Maradzi (MB-candidate stock).")
a("PH manifesto launch (20 Jul, continuity of Tok Min)","PIR-07","positive",0.32,"improving","none",5,"rev13 +0.30 -> rev14 +0.32. BH+Awani+NST+The Edge+Metro: PH launch manifesto malam esok (20 Jul), officiated Amirudin Shari. Centres on 'kesinambungan pentadbiran Aminuddin (Tok Min) sebagai MB'. Contrasts with BN 24 Jul DUN Linggi launch.")
a("BN manifesto launch 24 Jul (DUN Linggi + Pertang)","PIR-07","neutral",0.18,"improving","none",4,"rev13 +0.15 -> rev14 +0.18. 4-source corroborated (Kosmo+The Vibes+prior intel+NST gnews). At DUN Linggi + Pertang. WATCH: will it become JOINT BN-PN launch given Annuar 'manifesto bersepadu' + 'kongsi pentas' confirmation? Upcoming (5 days).")
a("Amirudin Shari (Selangor MB, PH NS ops Co-Director)","PIR-07","positive",0.30,"stable","none",1,"Selangor MB / PH Majlis Presiden member; Co-Director PH NS PRN operations. Will officiate PH manifesto launch 20 Jul.")
a("Muhammad Zaki Md Sabri (PH media secretariat chief)","PIR-07","neutral",0.15,"stable","none",1,"PH NS Media Secretariat chief / Bilik Gerakan director. Briefed PH manifesto launch; police report over insult to Yang di-Pertuan Besar NS; urged avoidance of 3R issues.")
a("Day-1 campaign operations (evening dispatch, 19 permits)","PIR-07","positive",0.45,"improving","none",3,"Carried rev13. Evening Day-1 dispatch (18:00-22:15 MYT): 19 permits approved (2 cancelled); Tok Mat resign-acceptance (19:28-21:03 FRESHEST NST 21:03); PH manifesto launch eve; Klawang cousins peaceful; Loke Day-1 walkabout; Teo Nie Ching PH dinner capstone (22:07). 171500: Khaled 'KO habis' + Loke '23 kerusi' + 'not in Rantau' extend the dispatch window to 00:21 MYT. Mature-campaign framing dominant.")
a("Alzafny Ahmad (NS police chief)","PIR-07","neutral",0.20,"stable","none",2,"Carried rev13. NST (19 Jul 12:26): 19 campaign permits approved; 1 election-offense report (verbal dispute, no investigation paper); social-media incitement warning.")
a("19 campaign permits approved","PIR-07","positive",0.30,"stable","none",2,"NS police received 19 ceramah permit applications — ALL 19 APPROVED (NST 12:26+Kosmo 10:54). 1 election-offense report. Mature-campaign signal.")
a("103 candidates / 36 seats","PIR-07","neutral",0.10,"stable","none",1,"EC confirms 103 candidates / 36 seats (Focus Malaysia 18 Jul); 11 straight fights, 21 three-cornered, 2 four-cornered, 2 five-cornered (Nilai+Sri Tanjung); 889,490 voters; polling Aug 1, early voting July 28.")
a("Fadillah (DPM, Anwar discipline discussion)","PIR-07","neutral",0.10,"stable","none",1,"DPM; mentioned in Anwar resign-to-attack / unity-govt discipline discussion context.")
a("Tamim Dahri Abd Razak (land activist, remand)","PIR-07","neutral",-0.10,"stable","none",1,"Land activist / independent; surrendered to police, remand 2 days (Awani 19 Jul). Tangential NS political figure.")
a("Mazalan Maarop (Seremban Umno chief)","PIR-07","neutral",0.10,"stable","none",1,"Seremban Umno chief; present at gabung-jentera (NST 19:49) with Hamzah, Takiyuddin, Kiandee.")
a("BN confident of winning alone","PIR-07","neutral",0.15,"stable","none",1,"The Edge (18 Jul): BN confident of winning enough seats to form NS govt ALONE — contrasts with joint-manifesto + machinery-merger; tension between 'go-alone' confidence and 'joint BN-PN' operationalization.")
# NEW PIR-07 entities
a("N.19 Johol (Saiful Yazan vs Mohd Zailan, straight fight)","PIR-07","neutral",0.10,"stable","none",2,"NEW. DUN Johol (N.19). Site of Khaled Nordin's BN machinery launch (Majlis Pengenalan Calon & Pelancaran Jentera BN DUN Johol, 19 Jul). Straight fight: Saiful Yazan Sulaiman (BN incumbent, Datuk) vs Mohd Zailan Mohd Munawar (PH). Khaled: Johol Malay-majority; 'gelombang Melayu' sentiment felt here. T1 seat.")
a("Saiful Yazan Sulaiman (BN Johol incumbent)","PIR-07","neutral",0.10,"stable","none",1,"NEW. BN incumbent candidate DUN Johol (N.19), Datuk. Introduced by Khaled at BN machinery launch. Khaled frames him as beneficiary of 'tak nak UMDAP' Malay sentiment — voters who dislike PH (contains DAP) will choose Saiful.")
a("Mohd Zailan Mohd Munawar (PH Johol)","PIR-07","neutral",0.05,"stable","none",1,"NEW. PH candidate DUN Johol (N.19). Straight fight vs BN incumbent Saiful Yazan Sulaiman.")
a("Aminuddin small-group campaign style (caretaker no advantage)","PIR-07","neutral",0.10,"stable","priority",1,"NEW. Aminuddin (Metro 16:47 MYT): prefers small-group campaigning (2-3 people) at Linggi — 'sejak 2008 saya berkempen macam ini.' Explicitly states caretaker MB status gives NO advantage: 'MB pun sekarang dah dipanggil caretaker saja... saya tidak boleh buat apa-apa keputusan.' Acknowledges Linggi traditionally BN stronghold. Positive Indian voter reception at Pekan Pasir Panjang. Director 'fleeing Sikamat' adjacent. [PRIORITY].")
a("Aminuddin honest-not-corrupt defense (Loke)","PIR-07","positive",0.30,"stable","priority",1,"NEW. Loke (NST+FMT 16:03) defends MB Aminuddin as PH MB-retention candidate: 'done nothing wrong, not corrupt, not abused position, humble, willing to work with everyone.' 'PH inclusive — represents all races.' Frames PH as seeking fresh mandate to retain Aminuddin as MB. Counter to BN-PN 'stability/Malay-unity' — PH's pitch = incumbent-performance continuity + inclusive governance. [PRIORITY].")
a("Loke transport-minister advantage for Chennah","PIR-07","positive",0.25,"stable","none",1,"NEW. Loke rebuts 'neglected Chennah' (NST+BH+Metro): as transport minister he channelled MORE benefits to Chennah incl. Kampung Madani projects. 'Highly dedicated full-time team.' Frames ministerial status as Chennah advantage. Counter to Director 'Chennah demographics risk' (Loke LOSES if PRU15 repeats).")

entities = E

# Condense rationales for none-alert entities to keep file under 100K read limit.
# Full rationales retained for critical/priority entities + key new entities.
for e in entities:
    if e["alert"] == "none":
        r = e["rationale"]
        # keep first ~38 chars + ellipsis for none-alert entities
        if len(r) > 42:
            e["rationale"] = r[:37].rstrip() + "..."


trend = {
  "pir_06": {
    "verdict": "[CRITICAL CARRIED + DEEPENED via Khaled Nordin BN-VP elimination call; BN-PN cooperation formalizes to 4th stage (kongsi pentas)]. rev14 ingests the 226-entity 1725 build (finalized 01:24 MYT 20 Jul — AFTER rev13's 23:30 MYT which used the 205-entity 1435 build). TWO new PIR-06 escalations: (1) Khaled Nordin (Umno VP/Defence Minister) 4-publisher anti-Bersatu ELECTORAL-ELIMINATION call 'Pastikan Bersatu di NS KO habis-habis' + 'kacau daun' (NST+BH+Metro+FMT 23:49-00:16 MYT) = FIRST BN-VP-level hard-news call for Bersatu's electoral wipeout. 6th trigger for Muhyiddin (-0.90->-0.92), 7th for Bersatu (-0.86->-0.88). [PRIORITY PIR-06] not [CRITICAL]: electoral-elimination rhetoric by a BN leader, NOT formal PN-MT expulsion. (2) PN 'kongsi pentas dengan BN' (Utusan 12:13) = 4TH STAGE of BN-PN cooperation formalization: seat-swap -> gabung-jentera (18:29) -> manifesto bersepadu (20:22) -> kongsi pentas. Central tension PERSISTS: BN-PN formalizes through 4 stages (machinery + joint manifesto + joint ceramah + MB concession) WHILE Bersatu declares lebih-hebat exit + sasar solo 24-seat + faces Hamzah rebuke + Khaled elimination — running in parallel on the same ballot. Formal PN-MT expulsion notice / Bersatu withdrawal STILL NOT DETECTED (11th consecutive pass).",
    "numeric_shift_check": "rev13 -> rev14 deltas: Muhyiddin -0.90 -> -0.92 (+2.2%), Bersatu -0.86 -> -0.88 (+2.3%), Bersatu-PN fracture -0.88 -> -0.89 (+1.1%), PN-removal -0.89 -> -0.90 (+1.1%), toxic PN -0.78 stable, kuorum -0.65 stable, RoS -0.62 stable, PAS -0.25 -> -0.22 (12% improving), Hadi -0.25 -> -0.22 (12% improving), BN +0.35 -> +0.40 (14.3% improving, Khaled+kongsi-pentas+joint-manifesto), gabung-jentera +0.45 -> +0.48 (6.7% improving, kongsi-pentas), joint-manifesto +0.45 -> +0.48 (6.7% improving), Hamzah -0.20 stable, Kiandee -0.25 stable, PN +0.30 stable, Wawasan -0.15 stable. NO single PIR-06 entity crosses the >30% numeric shift threshold this cycle. CRITICAL continues to fire via the QUALITATIVE 'Bersatu internal-fracture signal sharp-negative' rule (now multi-publisher hard-news confirmed across 7 converging triggers), NOT the numeric rule. The Khaled 'KO habis' elimination call is the substantive new signal DEEPENING the Bersatu sharp-negative trajectory.",
    "bersatu_sharp_negative": "YES — internal-fracture signal sharp-negative, multi-publisher hard-news CONFIRMED across SEVEN converging triggers: (1) quorum + RoS two-pronged, (2) 'lebih hebat' new-coalition, (3) 'sasar bentuk kerajaan' solo 24-seat bid, (4) 'PN toksik' framing, (5) 24 own-logo seats + analyst wipeout consensus + kacau daun, (6) Hamzah public rebuke, (7) KHALED NORDIN (BN VP/Defence Minister) 4-publisher 'KO habis' electoral-elimination call. -> [CRITICAL] per directive.",
    "lebih_hebat_new_coalition_sentiment": "Director-flagged. Multi-publisher hard-news (Sinar+BH+Metro+MalaysiaGazette+Newswav+Buletin TV3, 17 Jul) + >50% viral amplification. Scored -0.78 CRITICAL (carried). PRU16 realignment vehicle. No escalation 18-19 Jul — remains at hint/bayangan stage.",
    "sasar_bentuk_kerajaan_sentiment": "Director-flagged. MalaysiaGazette + Sinar (19 Jul 15:37-15:53) hard-news: Bersatu sasar bentuk kerajaan negeri, 24 kerusi. Director rule fires (hard-news = CRITICAL). Scored -0.80 CRITICAL (carried). 24 EXCEEDS simple-majority 19. 171500 NOTE: Loke 'PH sasar 23 kerusi' is PH-attributed safe-majority (scored separately PRIORITY PIR-16); the Bersatu-attributed 24-seat solo version remains the [CRITICAL] signal. DIRECTLY CONTRADICTS PN-MB-concedes-to-BN + joint-manifesto + kongsi-pentas.",
    "wawasan_admission_sentiment": "Director-flagged. Hamzah's Wawasan + Pejuang admitted into PN (FMT 22 Jun). Component-party churn. Scored -0.15 PRIORITY (carried). Wawasan+PAS bloc visibly stabilizes PN against Bersatu exit (Hamzah rebuke confirms).",
    "ros_complaint_disruption_sentiment": "Director-flagged. Two-pronged: (1) Kiandee RoS-intervention warning re: MPT quorum, (2) Tun Faisal RoS complaint disrupting PN seat negotiations. Scored RoS -0.62 CRITICAL (carried).",
    "pdm_klawang_reopen_sentiment": "Director-flagged. FMT (19 Jul 15:33): PDM Klawang tutup 'kerana tak faham kerjasama BN-PN' (Jalaluddin). Expects reopen 1-2 days. Grassroots-friction at N.28. Scored -0.22 PRIORITY WATCH (slight decline). Monitor reopen.",
    "toxic_termination_pecat_kuorum_lebih_hebat_trajectory": "'toxic PN' multi-publisher (Muhyiddin) DEEPENED -0.78 CRITICAL (carried). 'lebih hebat' = multi-publisher CRITICAL -0.78 (carried). 'kuorum' = Director-designated CRITICAL, two-pronged RoS pressure, -0.65 (carried). 'pecat' trajectory: Hamzah (Feb), Wan Saiful (Oct), Tang Jay Son (Gerakan 18 Jul) -0.40. 'termination' = formal PN-MT notice STILL 0 (11 passes). Trajectory: pre-threshold, escalating tier-by-tier; most likely Bersatu voluntary realignment AFTER Aug 1 poll. NEW THIS CYCLE: Khaled Nordin 'KO habis' electoral-elimination call — adds BN-VP voice to the anti-Bersatu trajectory (electoral, not coalition-membership).",
    "threshold_status": "Formal pecat/termination NOT crossed. Trajectory deepening via Khaled elimination call. 7 converging [CRITICAL] triggers; formal PN-MT expulsion notice absent 11 cycles. Most likely Bersatu voluntary realignment AFTER 1 Aug poll.",
    "bn_pn_cooperation_4_stages": "NEW TRAJECTORY MAP. BN-PN cooperation formalizes through 4 stages this cycle: (1) seat-swap (BN 25 / PN 11 / Bersatu 24 solo), (2) gabung-jentera machinery merger (Metro 18:29 + NST 19:49, +0.48 improving), (3) manifesto bersepadu joint manifesto (Metro 20:22 + NST 20:31, +0.48 improving), (4) kongsi pentas joint ceramah (Utusan 12:13, +0.40 improving NEW). Plus MB concession to BN (Jalaluddin). WATCH: will 24 Jul BN manifesto launch at DUN Linggi become a JOINT BN-PN event? This 4-stage formalization runs IN PARALLEL with the Bersatu-exit trajectory (lebih-hebat + sasar + PN-toksik + Hamzah rebuke + Khaled elimination) on the same ballot — the central PIR tension.",
    "khaled_nordin_anti_bersatu_escalation": "NEW MAJOR signal. Khaled Nordin (Umno VP / Defence Minister, MP Kota Tinggi) 4-publisher (NST+BH+Metro+FMT, 23:49-00:16 MYT 19-20 Jul): 'Pastikan BERSATU di Negeri Sembilan KO habis-habis' / 'make sure Bersatu gets knocked out completely' + 'kacau daun' + 'ditubuhkan nak ganti UMNO'. FIRST BN-VP-level hard-news call for Bersatu's ELECTORAL ELIMINATION. Pairs with 'gelombang Melayu ke BN' (BH+Metro 00:13-00:56). Dismisses AMK resign-call. Spoke at Johol BN machinery launch. Classified [PRIORITY PIR-06] NOT [CRITICAL] — Director PIR-06 keywords 'keluar/pecat/tarik diri' = coalition-membership actions; this is electoral-elimination rhetoric by a BN (not PN) leader. Scored -0.55 (Bersatu KO habis narrative) + -0.30 (Khaled personally).",
    "offsetting_signals": "BN-PN operational arrangement DEEPENS to 4 stages this cycle: (1) gabung-jentera +0.48, (2) joint-manifesto +0.48, (3) kongsi-pentas +0.40 NEW, (4) MB concession. Plus Khaled 'gelombang Melayu ke BN' +0.35 (pro-BN-PN). Hassan Karim (PKR MP) intra-PH dissent vs AMH adds nuance to resign-narrative. These DEEPEN coalition-arrangement cooperation (NOT Bersatu-internal-fracture dimension). Central tension: BN-PN formalizes through 4 stages WHILE Bersatu declares exit trajectory + faces Khaled elimination call — running in parallel on the same ballot."
  },
  "pir_16": {
    "verdict": "[CRITICAL CARRIED — 'sasar bentuk kerajaan' + 'lebih hebat' persist at CRITICAL; 'Bersatu kacau daun' UPGRADED with FIRST BN-VP hard-news corroboration; resign-narrative chain enriched with Hassan Karim PKR dissent + Nga pledge context; PH counter-narrative strengthens via 'PH sasar 23 kerusi' + 'campaign on policies' + 'not in Rantau' + election-origin framing]. rev14: 'sasar bentuk kerajaan negeri' (Bersatu, MalaysiaGazette) + 'lebih hebat new coalition' (multi-publisher, >50% viral) both persist at [CRITICAL]. 'Bersatu kacau daun' ESCALATES -0.50 -> -0.58 (PRIORITY) — Khaled Nordin 4-publisher hard-news = FIRST BN-VP-level corroboration of this PIR-16 keyword (previously only Wan Saiful Metro 16:31); challenges 'penyatuan undi Melayu' (+0.20 -> +0.15 declining). 'Bersatu in disarray' bundle deepens -0.65 -> -0.70. Resign-narrative chain ENRICHED: AMH -> Anwar -> Tok Mat -> Akmal -> Hassan Karim (PKR dissent) + Nga pledge (Johor precondition) + Khaled dismisses AMK. NEW PH counter-narratives: 'PH sasar 23 kerusi' safe-majority (Loke 5-publisher, +0.25 — PH-attributed so PRIORITY not CRITICAL per Director rule); 'campaign on policies not personal attacks' (+0.40); 'not campaigning in Rantau' (+0.30 — notable intra-unity-govt restraint, PH leader ceding battleground to BN partner); April 19 royal crisis + 14 Umno ADUN withdrew + 5 PN backdoor attempt = election ORIGIN story (Loke NST+FMT 16:03). MCA biggest-loser rebuttal = containment (MCA -0.45 -> -0.48 deepening); Saw Yee Fung vs Chong Sin Woon WhatsApp viral (9,100 likes) = FIRST concrete MCA-leader pushback vs BN-PN/PAS.",
    "viral_amplification_gt50": "FIRED for 'lebih hebat' (6+ outlets, multiple editions, one cycle). 'Bersatu in disarray' bundle (Wan Saiful kacau daun + Khaled 'KO habis' + Kiandee + resignations + analyst wipeout + Hamzah rebuke) amplifies across PIR-06+16. NEW: Saw Yee Fung WhatsApp screenshot viral (9,100 likes) — intra-MCA friction amplifier.",
    "hard_news_corroboration_bersatu_exit_or_sasar": "FIRED (carried) — TWO signals: (1) 'sasar bentuk kerajaan negeri' (Bersatu-attributed, MalaysiaGazette + Sinar) = [CRITICAL]; (2) 'lebih hebat' (multi-publisher) = [CRITICAL]. The specific 'Bersatu exit imminent?' framing stays PRIORITY (viral-tier, 12th consecutive cycle no hard-news corroboration of THAT exact framing). NEW: 'Bersatu kacau daun' now has BN-VP hard-news (Khaled) — but is NOT in the Director CRITICAL trigger list, so stays PRIORITY.",
    "bersatu_kacau_daun_sentiment": "Director-flagged. ESCALATED -0.50 -> -0.58. UPGRADED 171500: Khaled Nordin (Umno VP/Defence Minister) 4-publisher 'Bersatu hanya kacau daun' (FMT BM+BH BM+Metro BM+NST EN, 23:49-00:16 MYT) = FIRST BN-VP-level hard-news corroboration of this PIR-16 narrative keyword. Plus Wan Saiful (Metro 19 Jul 16:31). Challenges 'penyatuan undi Melayu'. [PRIORITY] not [CRITICAL] (CRITICAL trigger = 'Bersatu exit imminent?' or 'sasar bentuk kerajaan' hard-news — neither newly crossed).",
    "sasar_vs_mb_after_prn_vs_joint_manifesto_vs_kongsi_pentas": "CENTRAL TENSION EXPANDED to 4-way. 'sasar bentuk kerajaan negeri' (-0.80 CRITICAL, Bersatu solo 24-seat bid) vs 'MB after PRN' (+0.15, PN concedes MB to BN) vs 'BN-PN joint manifesto' (+0.48, Annuar) vs 'kongsi pentas' (+0.40 NEW, Utusan). Bersatu's solo-governing bid DIRECTLY CONTRADICTS the PN-MB-concession, joint-manifesto, AND joint-ceramah. NEW: Loke 'PH sasar 23 kerusi' (+0.25) is the PH-attributed safe-majority version (PRIORITY not CRITICAL). The two [CRITICAL]-tier signals run in parallel on the same ballot.",
    "makmal_politik_sentiment": "Director-flagged. Hadi + Zahid + Zaharuddin Sani + Zan Azlee + Annuar + kongsi-pentas. NS PRN as political laboratory for PRU16. Consolidating (+0.25 improving). 'Ujian formula' stage per Syahir.",
    "mca_biggest_loser_and_rebuttal_trajectory": "Loke quote -0.52 (MCA defensive, deepening -0.45 -> -0.48). MCA rebuttal = Wee 'bukan perkara besar' containment + Saw Yee Fung told to skip NS (internal, Chong Sin Woon WhatsApp viral 9,100 likes) = CONTAINMENT not counter-attack. NEW: 'MCA told her to stay home' (TRP, -0.30) = FIRST concrete MCA-leader pushback vs BN-PN/PAS. Top leadership (Wee/Mah) still silent. Trajectory: declining (MCA).",
    "dap_coalition_intolerant_frame_13_duns": "Hadi 'reject unnatural Malay groups with DAP' targets 13 non-Malay DUNs. Frame -0.45 (carried). Counter: Lim Kit Siang rejects Islamophobia; Madani reforms (Teo). Frame intensifying, counter emerging.",
    "majoriti_mudah_vs_not_taking_for_granted": "'majoriti mudah' NOT yet quoted (latent, watch 24 Jul BN manifesto). 'not taking for granted' (Nazri 'tidak memandang mudah') + 'no easy path for political top guns' active. NEW: Loke 'PH sasar 23 kerusi' implicitly says 19 'majoriti mudah' NOT enough — frames 23 as safe. Director [PRIORITY] flags confirmed.",
    "resign_narrative_chain": "CHAIN ENRICHED this cycle: AMH joint statement (10:43) -> Anwar firewall (14:47) -> Tok Mat 'ready to resign' (19:28-21:03, 5-publisher incl Metro 19:42) -> Akmal 'I'll resign if Nga quits' (05:51-12:40 + NST 23:59 conditional) -> NEW: Hassan Karim (PKR MP) pushback 'Tak pelik... PH juga selepas PRU 2008' (FMT 15:00) + NEW: Nga resignation pledge (Johor precondition, Newswav+MSN 17 Jul) + NEW: Khaled dismisses AMK (Awani 23:36). Resign-narrative now has BOTH sides + intra-PH dissent (PKR old guard vs PH Youth). Polling day (Aug 1) is inflection point.",
    "madani_reforms_continuity_ph_counter": "Carried + strengthened. Teo Nie Ching (NST 22:07 + BH BM 22:35, now 2-publisher): PH mandate to continue Madani reforms; record highs; 10A SPM matriculation; DAP 'undeterred'. Scored +0.42 improving. NEW complements: Loke 'campaign on policies' (+0.40) + 'not in Rantau' (+0.30) + 'PH sasar 23 kerusi' (+0.25) + Aminuddin 'honest-not-corrupt' (+0.30). PH counter-narrative to BN-PN stability/Johor formula = incumbent-performance continuity + inclusive governance + clean campaign.",
    "april_19_royal_crisis_election_origin": "NEW MAJOR context. Loke (NST+FMT 16:03 MYT): April 19 2026 — NS's four undangs claimed Tuanku Muhriz removed as Yang di-Pertuan Besar, sparking royal+political crisis. Resulted in all 14 Umno ADUN withdrawing support for MB Aminuddin + 5 PN ADUN attempting 'backdoor government.' THE TRIGGER for Aug 1 NS PRN. Loke uses this to justify PH 'safe majority 23' target ('we did not want this election, but look what they did'). Core PH campaign narrative. [PRIORITY].",
    "new_narratives_surfacing_rev14": "Mohamed Khaled Nordin (anti-Bersatu elimination, 4-publisher) [NEW PIR-06 person]; Bersatu KO habis [NEW PIR-06 narrative]; gelombang Melayu ke BN [NEW PIR-06 narrative]; PN kongsi pentas dengan BN [NEW PIR-06 4th-stage formalization]; Khaled dismisses AMK [NEW PIR-06]; Hassan Karim (PKR dissent) [NEW PIR-06 person]; campaign on policies not personal attacks (Loke) [NEW PIR-16]; Loke not campaigning in Rantau [NEW PIR-16/PIR-07]; PH sasar 23 kerusi safe-majority [NEW PIR-16/PIR-07, 5-publisher]; MCA told her to stay home (Saw Yee Fung viral) [NEW PIR-16]; Teng Chang Khim [NEW PIR-16]; Nga resignation pledge (Johor precondition) [NEW PIR-16]; Tuanku Muhriz + April 19 royal crisis + 14 Umno ADUN withdrew + 5 PN backdoor [NEW PIR-16 election origin]; N.19 Johol + Saiful Yazan + Mohd Zailan [NEW PIR-07]; Aminuddin small-group campaign style [NEW PIR-07]; Aminuddin honest-not-corrupt defense [NEW PIR-07]; Loke transport-minister advantage Chennah [NEW PIR-07]."
  },
  "pir_07": {
    "verdict": "Evening Day-1 + early Day-2 enrichment continues; NO critical flag. No seat shows incumbent/leading-candidate sentiment drop >20% (Aminuddin +0.62 stable, Bakri Sawir +0.45 stable, Tok Mat +0.62 stable/improving). Director-flagged: Pertang 'derhaka' friction corroborated (BH+NST+Metro) = [PRIORITY] (active+corroborated, Jalaluddin rebuttal contains intensification); PDM Klawang shutdown/reopen persists (N.28 +0.30 -> +0.25 declining, incumbent unaffected). 'fleeing Sikamat' persists NOT intensifying (Aminuddin small-group campaign, caretaker no advantage). N.14 defector-framing ACTIVE NOT intensifying. NEW PIR-07: N.19 Johol straight fight (Saiful Yazan BN vs Mohd Zailan PH) + Aminuddin small-group campaign style + Aminuddin honest-not-corrupt defense (Loke) + Loke transport-minister advantage Chennah. Evening Day-1 dispatch extends to 00:21 MYT (Khaled 'KO habis' + Loke '23 kerusi' + 'not in Rantau'). BN manifesto launch 24 Jul (DUN Linggi + Pertang, JOINT BN-PN watch) + PH manifesto launch 20 Jul = upcoming. 171500 Harian Metro feed recovery (HTTP 200) resolved persistent blocker, recovering 17 new full-text articles.",
    "incumbent_drop_gt20": "NOT DETECTED (Aminuddin +0.62 stable; Bakri Sawir +0.45 stable; Tok Mat +0.62 stable/improving on 5-publisher resign-compliance incl Metro 19:42).",
    "pertang_derhaka_friction": "Director-flagged. Corroborated (BH+NST+Metro). Jalaluddin rebuttal 'tak masuk akal tuduh saya derhaka'. Onn Hafiz 'DNA UMNO bukan penderhaka' (BH 14:47). Director rule: 'derhaka' at Pertang = [PRIORITY]. Active+corroborated; rebuttal contains intensification. BN manifesto launch 24 Jul here (alongside Linggi).",
    "pdm_klawang_shutdown_reopen_impact": "Director-flagged. FMT (19 Jul 15:33): PDM Klawang tutup 'kerana tak faham kerjasama BN-PN'. Jalaluddin expects reopen 1-2 days. Grassroots-friction at N.28 (cousins race). Seat +0.30 -> +0.25 declining; incumbent Bakri Sawir unaffected (+0.45 stable). Monitor reopen.",
    "n14_defector_intensification": "NOT DETECTED (framing present, carryover, not intensifying). N.14 candidates CONFIRMED: Muhammad Nazri Kassim (PH, 'tidak memandang mudah' = Director [PRIORITY]) + Dr Rafie (PN/Wawasan, Hamzah met him). Priority-watch per directive.",
    "bn_manifesto_launch_24_jul": "UPCOMING (4 days) at DUN Linggi (N.32 — Aminuddin's seat) + Pertang. 4-source corroborated (Kosmo+The Vibes+prior intel+NST gnews). WATCH: will it become a JOINT BN-PN launch given Annuar 'manifesto bersepadu' + 'kongsi pentas' confirmation? Director-flagged. Scored +0.18 improving.",
    "ph_manifesto_launch_20_jul": "TODAY (20 Jul), officiated Amirudin Shari. 5-outlet corroborated (BH+Awani+NST+The Edge+Metro). Centres on 'kesinambunan Tok Min' (Aminuddin continuity). +0.32 improving. Cha Kee Chin (DAP NS sec) present.",
    "evening_day1_dispatch": "Extends to 00:21 MYT (Khaled 'KO habis' + Loke '23 kerusi' + 'not in Rantau' + 'campaign on policies'). 22:15 MYT window + 22:07 FRESHEST Teo Nie Ching. Positive: 19 permits approved, Tok Mat resign-acceptance 5-publisher (FRESHEST NST 21:03), PH manifesto launch eve, Klawang cousins peaceful, Loke Day-1 walkabout, Madani reforms pitch. Mature-campaign framing dominant. +0.45 improving. Full 36-seat PIR-07 map populated; N.19 Johol added this cycle."
  },
  "delta_vs_rev13": {
    "new_entities_rev14": [
      "Mohamed Khaled Nordin (Umno VP/Defence Minister) — [NEW PIR-06 person, 4-publisher anti-Bersatu 'KO habis'/'kacau daun' electoral-elimination call]",
      "Hassan Karim (PKR MP Pasir Gudang) — [NEW PIR-06 person, intra-PH dissent vs AMH resign-call]",
      "Bersatu KO habis (electoral-elimination call) — [NEW PIR-06 narrative]",
      "gelombang Melayu ke BN — [NEW PIR-06 narrative, Khaled pro-BN Malay-unity]",
      "PN kongsi pentas dengan BN (joint ceramah) — [NEW PIR-06 4th-stage cooperation formalization]",
      "Khaled dismisses AMK resign-call — [NEW PIR-06 friction axis]",
      "campaign on policies not personal attacks (Loke) — [NEW PIR-16, clean-campaign signal]",
      "Loke not campaigning in Rantau (unity-govt harmony) — [NEW PIR-16/PIR-07, PH restraint ceding battleground]",
      "PH sasar 23 kerusi (safe majority / 8123) — [NEW PIR-16/PIR-07, 5-publisher, PH-attributed safe-majority]",
      "MCA told her to stay home (Saw Yee Fung vs Chong Sin Woon) — [NEW PIR-16 intra-MCA viral, 9,100 likes]",
      "Teng Chang Khim — [NEW PIR-16 person, DAP challenger to Akmal]",
      "Nga resignation pledge (Johor precondition) — [NEW PIR-16 narrative context]",
      "Tuanku Muhriz Tuanku Munawir — [NEW PIR-16 person, royal context]",
      "April 19 royal crisis (4 undangs claim Tuanku Muhriz removed) — [NEW PIR-16 election origin story]",
      "14 Umno ADUN withdrew support + 5 PN backdoor attempt — [NEW PIR-16/PIR-07 PH campaign narrative]",
      "N.19 Johol (Saiful Yazan BN vs Mohd Zailan PH, straight fight) — [NEW PIR-07 seat]",
      "Saiful Yazan Sulaiman (BN Johol incumbent) — [NEW PIR-07 person]",
      "Mohd Zailan Mohd Munawar (PH Johol) — [NEW PIR-07 person]",
      "Aminuddin small-group campaign style (caretaker no advantage) — [NEW PIR-07 narrative]",
      "Aminuddin honest-not-corrupt defense (Loke) — [NEW PIR-07 narrative]",
      "Loke transport-minister advantage for Chennah — [NEW PIR-07 narrative]"
    ],
    "revised_entities_rev14": [
      "Muhyiddin Yassin: -0.90 -> -0.92 (SIXTH converging CRITICAL trigger: Khaled 'KO habis' elimination call)",
      "Bersatu: -0.86 -> -0.88 (SEVENTH trigger: Khaled 'KO habis' + 'kacau daun')",
      "Bersatu-PN fracture (3-sided): -0.88 -> -0.89 (Khaled adds BN-voice to fracture)",
      "PN-removal-of-Bersatu thread: -0.89 -> -0.90 (Khaled elimination rhetoric)",
      "PAS: -0.25 -> -0.22 (improving, Khaled pro-BN-PN + kongsi-pentas)",
      "Hadi Awang: -0.25 -> -0.22 (improving)",
      "BN: +0.35 -> +0.40 (improving, Khaled + kongsi-pentas + joint-manifesto + gelombang Melayu)",
      "MCA: -0.45 -> -0.48 (declining, Saw Yee Fung viral internal friction)",
      "Bersatu kacau daun: -0.50 -> -0.58 (ESCALATED, FIRST BN-VP Khaled hard-news corroboration)",
      "Bersatu in disarray: -0.65 -> -0.70 (Khaled 'KO habis' deepens)",
      "Bersatu heading for wipeout: -0.70 -> -0.72 (Khaled 'KO habis' reinforces)",
      "gabung jentera: +0.45 -> +0.48 (improving, kongsi-pentas 4th stage)",
      "BN-PN joint manifesto: +0.45 -> +0.48 (improving, kongsi-pentas)",
      "penyatuan undi Melayu: +0.20 -> +0.15 (further declining, Khaled elimination rhetoric frames Bersatu as splitter)",
      "Anthony Loke: +0.50 -> +0.52 (improving, 'campaign on policies' + '23 kerusi' + 'not in Rantau' + Chennah rebuttal)",
      "Madani reforms continuity (Teo): +0.40 -> +0.42 (improving, BH BM corroboration 2-publisher)",
      "Teo Nie Ching: +0.40 -> +0.42 (improving)",
      "MCA biggest loser: -0.50 -> -0.52 (declining, Saw Yee Fung viral)",
      "PDM Klawang shutdown: -0.20 -> -0.22 (slight decline, persists)",
      "N.28 Klawang: +0.30 -> +0.25 (declining, PDM friction)",
      "Saw Yee Fung: -0.20 -> -0.22 (declining, viral WhatsApp)",
      "PH manifesto launch: +0.30 -> +0.32 (improving, 5-outlet)",
      "BN manifesto launch 24 Jul: +0.15 -> +0.18 (improving, 4-source + kongsi-pentas)",
      "PH: +0.40 -> +0.42 (improving, Loke '23 kerusi' + 'campaign on policies')",
      "Chennah demographics risk: -0.30 -> -0.28 (slight ease, Loke transport-minister rebuttal)"
    ]
  },
  "collection_limitations": [
    "rev14 ingests the 226-entity 1725 build (finalized 01:24 MYT 20 Jul, cycles 153300+171500 = 23:33+01:15 MYT). rev13 (23:30 MYT 19 Jul) used the 205-entity 1435 build (finalized 22:41 MYT) — the 1725 build superseded it ~43 min after rev13's generation with +21 new entities + 13 context updates from the Harian Metro feed recovery (171500, HTTP 200, 17 new full-text articles).",
    "171500 Harian Metro feed recovery (www.hmetro.com.my/feed HTTP 200) resolves the persistent HTTP 000 blocker that had affected Metro across prior cycles — 17 new full-text articles recovered including gabung-jentera + manifesto bersepadu + Khaled 'KO habis'/'gelombang Melayu' + Tok Mat 5th outlet + Aminuddin small-group.",
    "Kiandee quorum attack (NST) remains headline-intelligence only (gnews JS-rendered; NST feed rotated) — sentiment at title-level inference for NST-specific items; FMT full text provides Kiandee corroboration.",
    "'sasar bentuk kerajaan negeri' relies on MalaysiaGazette + Sinar hard-news (19 Jul 15:37-15:53) — high-confidence per Director rule. Loke 'PH sasar 23 kerusi' (5-publisher) is PH-attributed safe-majority (23 seats, NOT 24 Bersatu solo) — scored PRIORITY PIR-16 NOT CRITICAL per Director rule (only Bersatu-attributed 'sasar' = CRITICAL). Additional hard-news corroboration across NST/Star/Utusan for the Bersatu version NOT yet detected.",
    "mkini 'Bersatu exit imminent?' SNAPSHOT body paywalled — preview only; reclassified PRIORITY (viral-tier) precisely because hard-news corroboration of THAT exact framing is absent 12 cycles (substantive exit content IS hard-news-corroborated via lebih-hebat + sasar).",
    "'barking dogs' (Albert Tei) full body NOT fetched (paywalled) — headline+description derived. Mandatory gnews query returned 0 fresh items across cycles.",
    "Director-list seats N.20 Bembang — candidate detail still NOT recovered; 'N.20 Bembang'<->'Bahau' mapping unconfirmed. N.15 Juasseh, N.27 Chembong limited discrete coverage. N.19 Johol added this cycle (Khaled machinery launch).",
    "Mah Hang Soon response to Loke 'biggest loser' NOT surfaced as fresh across 10 cycles — watch next cycle. 'sole opposition' (Muhyiddin) full frame partially derived; 153300 corroborated by The Vibes 18 Jul.",
    "Khaled 'KO habis'/'kacau daun' is 4-publisher hard-news (NST+BH+Metro+FMT) — FIRST BN-VP-level corroboration of 'Bersatu kacau daun' PIR-16 keyword. Classified [PRIORITY] not [CRITICAL]: Director PIR-06 keywords 'keluar/pecat/tarik diri' = coalition-membership actions; this is electoral-elimination rhetoric by a BN (not PN) leader. The CRITICAL Bersatu sharp-negative signal continues to fire via the qualitative 7-trigger rule.",
    "Score convention SIGNED per mission directive (rev1-9 unsigned; rev10+ converted); cross-revision numeric comparisons require sign-aware reading. rev13->rev14 deepens the Bersatu sharp-negative trajectory (Khaled 'KO habis' = 6th trigger for Muhyiddin, 7th for Bersatu).",
    "BN manifesto launch 24 Jul at DUN Linggi — 4-source corroborated (Kosmo+The Vibes+prior intel+NST gnews). HIGH-PRIORITY watch: will it become a JOINT BN-PN launch given Annuar 'manifesto bersepadu' + 'kongsi pentas' confirmation? The 4-stage formalization trajectory suggests it likely will.",
    "DAP/Nga Kor Meng response to Akmal's counter-resignation demand NOT yet detected — watch for response. Nga resignation pledge (Johor precondition) context added.",
    "Hassan Karim (PKR MP) intra-PH dissent vs AMH — adds nuance to resign-narrative (PKR old guard vs PH Youth). Director PIR-16 watch.",
    "Folder migration: rev14 writes to 2026-07-19 (hyphenated, per mission YYYY-MM-DD spec); earlier revisions remain in 20260719 (non-hyphenated). 20260716 sentiment-analysis 1-day gap remains unfilled (backfill directive)."
  ],
  "next_actions": [
    "PIR-06 (HIGHEST): Watch Bersatu Supreme Council formal response to Kiandee quorum + RoS two-pronged pressure (threshold-adjacent, 11 cycles no formal action). Monitor Muhyiddin 'lebih hebat'/'sasar kerajaan' formalization (the TWO CRITICAL hard-news signals). Watch 8 Bersatu-vs-PN direct-clash seats for campaign friction. Monitor PDM Klawang reopen (Jalaluddin expects 1-2 days). Monitor Hamzah-Muhyiddin intra-opposition warfare escalation. Watch BN-PN joint manifesto launch event (formalizes manifesto bersepadu). NEW: Monitor Khaled Nordin 'KO habis' electoral-elimination rhetoric escalation — does it draw Bersatu/Muhyiddin response? Watch 24 Jul BN manifesto launch — JOINT BN-PN event? (kongsi-pentas 4th stage suggests likely).",
    "PIR-16 (HIGHEST): Track whether 'sasar bentuk kerajaan' + 'lebih hebat' escalate from hard-news-corroboration tier to FORMAL withdrawal/pecat notice (next tier) — would shift 'Bersatu exit imminent?' from PRIORITY to CRITICAL. MCA rebuttal watch — Loke 'biggest loser' likely draws Wee/Mah Hang Soon counter (Saw Yee Fung viral amplifies from inside, 9,100 likes). Track 'Bersatu kacau daun' (now BN-VP Khaled + Wan Saiful) vs 'penyatuan undi Melayu' (further challenged +0.20->+0.15). Track 'DAP coalition-intolerant' vs Lim Kit Siang + Madani reforms counter across 13 non-Malay DUNs. Watch 'majoriti mudah' at BN manifesto launch 24 Jul. NEW: Track Loke 'PH sasar 23 kerusi' safe-majority framing (PH counter to BN 'majoriti mudah'). NEW: Track 'campaign on policies not personal attacks' + 'not in Rantau' — PH restraint signal; does BN-PN reciprocate? NEW: Track Hassan Karim PKR dissent vs AMH — intra-PH friction. NEW: Track April 19 royal crisis + 14 Umno ADUN backdoor framing as PH core campaign narrative.",
    "PIR-07: Capture Day-2 ceramah for T1 seats — Klawang (cousins + PDM reopen), Linggi (Aminuddin + BN manifesto 24 Jul JOINT?), Sikamat, Chennah (Loke vs Siow, demographics risk + transport-minister rebuttal), Rantau (Tok Mat, Loke not campaigning here), Pertang (derhaka friction), Johol (NEW, Khaled machinery launch). Monitor BN manifesto launch 24 Jul (DUN Linggi — JOINT BN-PN?) + PH manifesto launch 20 Jul for narrative shifts. Monitor Pertang derhaka intensification (currently contained). Watch Nga Kor Meng response to Akmal counter-demand. NEW: Full 36-seat map populated + N.19 Johol — capture Day-2 for razor-margin Kota (135-vote) + 5-corner Nilai/Sri Tanjung + Aminuddin small-group Linggi.",
    "Backfill the 20260716 sentiment-analysis gap (1-day gap in time series). Reconcile the 2026-07-19 (hyphenated) vs 20260719 (non-hyphenated) folder migration — rev14 writes to 2026-07-19 per mission YYYY-MM-DD spec; prior revisions remain in 20260719."
  ]
}

doc = {
    "metadata": meta,
    "entities": entities,
    "trend_summary": trend
}

# Cap verbose trend_summary strings to keep file under 100K read limit.
# Verdicts (key thesis) capped at 720 chars; other sub-keys at 300.
def cap(obj, vlimit=420, klimit=200):
    for k, v in obj.items():
        if isinstance(v, dict):
            cap(v, vlimit, klimit)
        elif isinstance(v, str):
            lim = vlimit if k == "verdict" else klimit
            if len(v) > lim + 5:
                obj[k] = v[:lim].rstrip() + "..."
        elif isinstance(v, list):
            obj[k] = [ (cap(x,vlimit,klimit) if isinstance(x,dict) else (x[:klimit-3]+"..." if isinstance(x,str) and len(x)>klimit else x)) for x in v ]
    return obj
trend = cap(trend)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(doc, f, ensure_ascii=False, indent=2)

size = os.path.getsize(OUT)
print(f"WROTE {OUT}")
print(f"entities={len(entities)} size={size} bytes ({size/1024:.1f} KB)")
# count alerts
cc = sum(1 for e in entities if e["alert"]=="critical")
pc = sum(1 for e in entities if e["alert"]=="priority")
nc = sum(1 for e in entities if e["alert"]=="none")
print(f"alert counts: critical={cc} priority={pc} none={nc}")
print(f"under 100K read limit: {size < 100000}")
